/* Bitmap.chpl:1 */
static void chpl__init_Bitmap(int64_t _ln_chpl,
                              int32_t _fn_chpl) {
  _ref_int32_t refIndentLevel_chpl = NULL;
  if (chpl__init_Bitmap_p) {
    goto _exit_chpl__init_Bitmap_chpl;
  }
  printModuleInit("%*s\n", "Bitmap", INT64(6));
  refIndentLevel_chpl = &moduleInitLevel;
  *(refIndentLevel_chpl) += INT64(1);
  chpl__init_Bitmap_p = UINT8(true);
  *(refIndentLevel_chpl) -= INT64(1);
  _exit_chpl__init_Bitmap_chpl:;
  return;
}

/* Bitmap.chpl:1 */
static void _construct_Bitmap_chpl(_ref__syncvar_uint64_t nBits_DOLLAR__chpl,
                                   _ref__domain_DefaultRectangularDom_1_int64_t_F bitmapSpace_chpl,
                                   _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t bitmap_chpl,
                                   _ref_Bitmap meme_chpl,
                                   _ref_Bitmap _retArg_chpl) {
  Bitmap_chpl this_chpl6;
  this_chpl6 = *(meme_chpl);
  (&this_chpl6)->nBits_DOLLAR__chpl = *(nBits_DOLLAR__chpl);
  (&this_chpl6)->bitmapSpace_chpl = *(bitmapSpace_chpl);
  (&this_chpl6)->bitmap_chpl = *(bitmap_chpl);
  *(_retArg_chpl) = this_chpl6;
  return;
}

/* Bitmap.chpl:1 */
static void chpl___ASSIGN_19(_ref_Bitmap _arg1_chpl,
                             chpl____wide__ref_Bitmap _arg2_chpl) {
  int32_t local_c_sublocid_any_chpl;
  int64_t local_dataParMinGranularity_chpl;
  chpl_bool local_dataParIgnoreRunningTasks_chpl;
  int64_t local_dataParTasksPerLocale_chpl;
  _ref__syncvar_uint64_t call_tmp_chpl = NULL;
  _syncvar_uint64_t coerce_tmp_chpl;
  _syncvar_uint64_t tmp_chpl;
  uint64_t coerce_tmp_chpl2;
  _ref__syncvar_uint64_t _ref_tmp__chpl = NULL;
  chpl____wide__ref__syncvar_uint64_t tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref__domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl2 = NULL;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F i_b_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl4 = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_b_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_object call_tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl7;
  chpl____wide_object tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_object call_tmp_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_object call_tmp_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl10;
  _ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl6 = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool ret_chpl4;
  int64_t call_tmp_chpl11;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl12;
  int64_t call_tmp_chpl13;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t _ref_tmp__chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl14;
  _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_a_chpl = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_b_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  _domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl15;
  _domain_DefaultRectangularDom_1_int64_t_F ret_tmp_chpl;
  _ref__domain_DefaultRectangularDom_1_int64_t_F ret_to_arg_ref_tmp__chpl = NULL;
  _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_arr_chpl = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_B_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl16;
  _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_a_chpl2 = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_b_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_a_chpl3 = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i_b_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  _domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl17;
  _domain_DefaultRectangularDom_1_int64_t_F ret_tmp_chpl2;
  _ref__domain_DefaultRectangularDom_1_int64_t_F ret_to_arg_ref_tmp__chpl2 = NULL;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl10 = {CHPL_LOCALEID_T_INIT, NULL};
  _tuple_2_star__ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl__iterLF;
  _ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i__e1_x_chpl = NULL;
  _array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t this_x1_chpl;
  _array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t this_x2_chpl;
  _array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl18;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t default_argtasksPerLocale_chpl;
  chpl_bool default_argignoreRunning_chpl;
  int64_t default_argminIndicesPerTask_chpl;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t this_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F coerce_tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_x1_chpl;
  _tuple_1_star_int64_t ret_tmp_chpl3;
  _ref__tuple_1_star_int64_t ret_to_arg_ref_tmp__chpl3 = NULL;
  chpl_localeID_t _autoCopy_tmp__chpl;
  chpl____wide_locale call_tmp_chpl19 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t ret_chpl8;
  chpl_bool call_tmp_chpl20;
  chpl____wide_locale call_tmp_chpl21 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_localeID_t _autoCopy_tmp__chpl2;
  chpl____wide_locale call_tmp_chpl22 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl11;
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t ret_x1_chpl;
  int64_t ret_x2_chpl;
  chpl_bool call_tmp_chpl23;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl24 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F i_ranges_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  _tuple_2_star_int64_t ret_tmp_chpl4;
  _ref__tuple_2_star_int64_t ret_to_arg_ref_tmp__chpl4 = NULL;
  int64_t numChunks_chpl;
  int64_t parDim_chpl;
  chpl_bool call_tmp_chpl25;
  range_int64_t_boundedLow_F ret_tmp_chpl5;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp__chpl5 = NULL;
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl26 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl27 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl28;
  range_int64_t_bounded_F ret_tmp_chpl6;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl6 = NULL;
  _array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl29;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  _array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl30;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl10 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t _ic__F0_this_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  _tuple_1_star_range_int64_t_bounded_F _ic__F7_block_chpl;
  int64_t _ic__F9_i_chpl;
  int64_t _ic__F10_end_chpl;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t _ic__F0_this_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  _tuple_1_star_range_int64_t_bounded_F _ic__F7_block_chpl2;
  int64_t _ic__F9_i_chpl2;
  chpl____wide_DefaultRectangularDom_1_int64_t_F coerce_tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl31 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  range_int64_t_bounded_F followThis_x1_chpl;
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl32 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl10 = {CHPL_LOCALEID_T_INIT, NULL};
  range_int64_t_bounded_F followThis_x1_chpl2;
  range_int64_t_bounded_F ret_tmp_chpl7;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl7 = NULL;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl12 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref__tuple_1_star_range_int64_t_bounded_F tmp_chpl13 = NULL;
  _tuple_1_star_int64_t ret_tmp_chpl8;
  _ref__tuple_1_star_int64_t ret_to_arg_ref_tmp__chpl8 = NULL;
  range_int64_t_bounded_F ret_tmp_chpl9;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl9 = NULL;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl33 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl14;
  int64_t ret_chpl11;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl34 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl15;
  _ref_range_int64_t_bounded_F i_x_chpl = NULL;
  range_int64_t_bounded_F tmp_chpl16;
  range_int64_t_bounded_F _ic__F0_this_chpl3;
  int64_t ret_chpl12;
  chpl____wide_DefaultRectangularDom_1_int64_t_F coerce_tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl35 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl11 = {CHPL_LOCALEID_T_INIT, NULL};
  range_int64_t_bounded_F followThis_x1_chpl3;
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl36 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl12 = {CHPL_LOCALEID_T_INIT, NULL};
  range_int64_t_bounded_F followThis_x1_chpl4;
  range_int64_t_bounded_F ret_tmp_chpl10;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl10 = NULL;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl17 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref__tuple_1_star_range_int64_t_bounded_F tmp_chpl18 = NULL;
  _tuple_1_star_int64_t ret_tmp_chpl11;
  _ref__tuple_1_star_int64_t ret_to_arg_ref_tmp__chpl11 = NULL;
  range_int64_t_bounded_F ret_tmp_chpl12;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl12 = NULL;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl37 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl19;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl38 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl20;
  _ref_range_int64_t_bounded_F i_x_chpl2 = NULL;
  range_int64_t_bounded_F tmp_chpl21;
  range_int64_t_bounded_F _ic__F0_this_chpl4;
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl22 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl39 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl23 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl40 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t tmp_chpl24;
  int64_t tmp_chpl25;
  int64_t tmp_chpl26;
  _tuple_1_star_range_int64_t_bounded_F locBlock_chpl;
  range_int64_t_bounded_F ret_tmp_chpl13;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl13 = NULL;
  range_int64_t_boundedLow_F ret_tmp_chpl14;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp__chpl14 = NULL;
  chpl____wide__ref_range_int64_t_bounded_F call_tmp_chpl41 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularDom_1_int64_t_F this_chpl13 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F call_tmp_chpl42 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl43;
  range_int64_t_bounded_F ret_tmp_chpl15;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl15 = NULL;
  range_int64_t_bounded_F tmpIter_chpl;
  range_int64_t_boundedLow_F ret_tmp_chpl16;
  _ref_range_int64_t_boundedLow_F ret_to_arg_ref_tmp__chpl16 = NULL;
  range_int64_t_bounded_F ret_tmp_chpl17;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl17 = NULL;
  chpl___EndCount_atomic_int64_int64_t _coforallCount_chpl = NULL;
  chpl___EndCount_atomic_int64_int64_t this_chpl14 = NULL;
  c_void_ptr cast_tmp_chpl;
  atomic_int64 _init_class_tmp__chpl;
  atomic_int64 this_chpl15;
  atomic_int_least64_t ret_chpl13;
  atomic_int_least64_t type_tmp_chpl;
  _ref_atomic_int_least64_t _ref_tmp__chpl3 = NULL;
  atomic_int64 ret_tmp_chpl18;
  _ref_atomic_int64 ret_to_arg_ref_tmp__chpl18 = NULL;
  c_void_ptr call_tmp_chpl44;
  chpl___EndCount_atomic_int64_int64_t wrap_call_tmp_chpl = NULL;
  int64_t numTasks_chpl;
  _ref_range_int64_t_bounded_F _ref_tmp__chpl4 = NULL;
  int64_t call_tmp_chpl45;
  chpl____wide__ref_range_int64_t_bounded_F tmp_chpl27 = {CHPL_LOCALEID_T_INIT, NULL};
  range_int64_t_bounded_F _ic__F0_this_chpl5;
  int64_t i_chpl;
  int64_t end_chpl;
  _class_localscoforall_fn6 _args_forcoforall_fn_chpl = NULL;
  _ref__tuple_2_star__ref__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t tmp_chpl28 = NULL;
  c_void_ptr _args_vforcoforall_fn_chpl;
  int64_t _taskListNodecoforall_fn_chpl;
  _ref_atomic_int64 _field_destructor_tmp__chpl = NULL;
  _ref_atomic_int_least64_t call_tmp_chpl46 = NULL;
  chpl_localeID_t call_tmp_chpl47;
  chpl___EndCount_atomic_int64_int64_t rvfDerefTmp_chpl = NULL;
  chpl_bool isdirect_chpl;
  chpl____wide__EndCount_atomic_int64_int64_t tmp_chpl29 = {CHPL_LOCALEID_T_INIT, NULL};
  _class_localson_fn104 _args_foron_fn_chpl = NULL;
  chpl____wide__EndCount_atomic_int64_int64_t tmp_chpl30 = {CHPL_LOCALEID_T_INIT, NULL};
  c_void_ptr _args_vforon_fn_chpl;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5574;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5575;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5576;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5577;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5578;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5579;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5580;
  chpl____wide_object chpl_macro_tmp_5581;
  chpl____wide__nilType chpl_macro_tmp_5582;
  chpl____wide_object chpl_macro_tmp_5583;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5584;
  chpl____wide_object chpl_macro_tmp_5585;
  chpl____wide_object chpl_macro_tmp_5586;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5587;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5588;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5589;
  chpl____wide__ref__wide_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5590;
  chpl____wide__ref_int32_t chpl_macro_tmp_5591;
  int32_t chpl_macro_tmp_5592;
  chpl____wide__ref_int64_t chpl_macro_tmp_5593;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5594;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5595;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5596;
  chpl____wide__ref__wide_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5597;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5598;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5599;
  chpl____wide__ref_int64_t chpl_macro_tmp_5600;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5601;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5602;
  chpl____wide__ref_int64_t chpl_macro_tmp_5603;
  chpl____wide__ref__wide_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5604;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5605;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5606;
  chpl____wide__ref_int64_t chpl_macro_tmp_5607;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5608;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5609;
  chpl____wide__ref_int64_t chpl_macro_tmp_5610;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5611;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5612;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5613;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5614;
  uint64_t chpl_macro_tmp_5615;
  chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F chpl_macro_tmp_5616;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5617;
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_5618;
  chpl__class_localscoforall_fn6_object chpl_macro_tmp_5619;
  chpl____wide__EndCount_atomic_int64_int64_t chpl_macro_tmp_5620;
  chpl__class_localson_fn104_object chpl_macro_tmp_5621;
  chpl____wide__EndCount_atomic_int64_int64_t chpl_macro_tmp_5622;
  local_c_sublocid_any_chpl = c_sublocid_any;
  local_dataParMinGranularity_chpl = dataParMinGranularity;
  local_dataParIgnoreRunningTasks_chpl = dataParIgnoreRunningTasks;
  local_dataParTasksPerLocale_chpl = dataParTasksPerLocale;
  call_tmp_chpl = &((_arg1_chpl)->nBits_DOLLAR__chpl);
  chpl_macro_tmp_5574.locale = (_arg2_chpl).locale;
  chpl_macro_tmp_5574.addr = &(((_arg2_chpl).addr)->nBits_DOLLAR__chpl);
  chpl_gen_comm_get(((void*)(&tmp_chpl)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5574).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5574).addr, sizeof(_syncvar_uint64_t), -1, COMMID(0), INT64(1), INT64(55));
  coerce_tmp_chpl = tmp_chpl;
  _ref_tmp__chpl = &coerce_tmp_chpl;
  chpl_macro_tmp_5575.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5575.addr = _ref_tmp__chpl;
  tmp_chpl2 = chpl_macro_tmp_5575;
  coerce_tmp_chpl2 = readFE(tmp_chpl2);
  chpl_macro_tmp_5576.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5576.addr = call_tmp_chpl;
  tmp_chpl3 = chpl_macro_tmp_5576;
  chpl___ASSIGN_7(tmp_chpl3, coerce_tmp_chpl2);
  call_tmp_chpl2 = &((_arg1_chpl)->bitmapSpace_chpl);
  chpl_macro_tmp_5577.locale = (_arg2_chpl).locale;
  chpl_macro_tmp_5577.addr = &(((_arg2_chpl).addr)->bitmapSpace_chpl);
  call_tmp_chpl3 = chpl_macro_tmp_5577;
  i_b_chpl = call_tmp_chpl3;
  chpl_macro_tmp_5578.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5578.addr = call_tmp_chpl2;
  tmp_chpl4 = chpl_macro_tmp_5578;
  chpl___ASSIGN_3(tmp_chpl4, i_b_chpl);
  call_tmp_chpl4 = &((_arg1_chpl)->bitmap_chpl);
  chpl_macro_tmp_5579.locale = (_arg2_chpl).locale;
  chpl_macro_tmp_5579.addr = &(((_arg2_chpl).addr)->bitmap_chpl);
  call_tmp_chpl5 = chpl_macro_tmp_5579;
  i_b_chpl2 = call_tmp_chpl5;
  chpl_macro_tmp_5580.locale = (i_b_chpl2).locale;
  chpl_macro_tmp_5580.addr = &(((i_b_chpl2).addr)->_instance);
  chpl_gen_comm_get(((void*)(&ret_chpl)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5580).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5580).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(1), INT64(1), INT64(55));
  chpl_macro_tmp_5581.locale = (&ret_chpl)->locale;
  chpl_macro_tmp_5581.addr = ((object)((&ret_chpl)->addr));
  call_tmp_chpl6 = chpl_macro_tmp_5581;
  chpl_macro_tmp_5582.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5582.addr = nil;
  chpl_macro_tmp_5583.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5583.addr = NULL;
  tmp_chpl5 = chpl_macro_tmp_5583;
  call_tmp_chpl7 = (! (((&call_tmp_chpl6)->addr != (&tmp_chpl5)->addr) || ((!(! (&call_tmp_chpl6)->addr)) && (chpl_nodeFromLocaleID(&((&call_tmp_chpl6)->locale), INT64(0), INT32(0)) != chpl_nodeFromLocaleID(&((&tmp_chpl5)->locale), INT64(0), INT32(0))))));
  if (call_tmp_chpl7) {
    goto _end__ASSIGN__chpl;
  }
  ret_chpl2 = (call_tmp_chpl4)->_instance;
  chpl_macro_tmp_5584.locale = (i_b_chpl2).locale;
  chpl_macro_tmp_5584.addr = &(((i_b_chpl2).addr)->_instance);
  chpl_gen_comm_get(((void*)(&ret_chpl3)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5584).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5584).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(2), INT64(1), INT64(55));
  chpl_macro_tmp_5585.locale = (&ret_chpl2)->locale;
  chpl_macro_tmp_5585.addr = ((object)((&ret_chpl2)->addr));
  call_tmp_chpl8 = chpl_macro_tmp_5585;
  chpl_macro_tmp_5586.locale = (&ret_chpl3)->locale;
  chpl_macro_tmp_5586.addr = ((object)((&ret_chpl3)->addr));
  call_tmp_chpl9 = chpl_macro_tmp_5586;
  call_tmp_chpl10 = (! (((&call_tmp_chpl8)->addr != (&call_tmp_chpl9)->addr) || ((!(! (&call_tmp_chpl8)->addr)) && (chpl_nodeFromLocaleID(&((&call_tmp_chpl8)->locale), INT64(0), INT32(0)) != chpl_nodeFromLocaleID(&((&call_tmp_chpl9)->locale), INT64(0), INT32(0))))));
  if (call_tmp_chpl10) {
    goto _end__ASSIGN__chpl;
  }
  tmp_chpl6 = call_tmp_chpl4;
  tmp_chpl7 = i_b_chpl2;
  chpl_macro_tmp_5587.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_5587.addr = tmp_chpl6;
  tmp_chpl8 = chpl_macro_tmp_5587;
  call_tmp_chpl11 = size4(tmp_chpl8);
  call_tmp_chpl12 = (call_tmp_chpl11 == INT64(0));
  if (call_tmp_chpl12) {
    call_tmp_chpl13 = size4(tmp_chpl7);
    ret_chpl4 = (call_tmp_chpl13 == INT64(0));
    goto _end__if_fn713_chpl;
  } else {
    ret_chpl4 = UINT8(false);
    goto _end__if_fn713_chpl;
  }
  _end__if_fn713_chpl:;
  if (ret_chpl4) {
    goto _end__ASSIGN__chpl;
  }
  _ref_tmp__chpl2 = i_b_chpl2;
  i_a_chpl = call_tmp_chpl4;
  i_b_chpl3 = _ref_tmp__chpl2;
  call_tmp_chpl14 = chpl__useBulkTransfer(i_a_chpl, i_b_chpl3);
  if (call_tmp_chpl14) {
    ret_chpl5 = (call_tmp_chpl4)->_instance;
    ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
    i_arr_chpl = call_tmp_chpl4;
    chpl_macro_tmp_5588.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_5588.addr = i_arr_chpl;
    tmp_chpl9 = chpl_macro_tmp_5588;
    chpl__getViewDom2(tmp_chpl9, ret_to_arg_ref_tmp__chpl);
    call_tmp_chpl15 = ret_tmp_chpl;
    i_B_chpl = i_b_chpl2;
    doiBulkTransfer2(ret_chpl5, i_B_chpl, &ret_tmp_chpl);
    chpl__autoDestroy5(&call_tmp_chpl15);
  } else {
    i_a_chpl2 = call_tmp_chpl4;
    i_b_chpl4 = _ref_tmp__chpl2;
    call_tmp_chpl16 = chpl__useBulkTransferStride(i_a_chpl2, i_b_chpl4);
    if (call_tmp_chpl16) {
      i_a_chpl3 = call_tmp_chpl4;
      i_b_chpl5 = i_b_chpl2;
      ret_chpl6 = (i_a_chpl3)->_instance;
      ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
      chpl_macro_tmp_5589.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_5589.addr = i_a_chpl3;
      tmp_chpl10 = chpl_macro_tmp_5589;
      chpl__getViewDom2(tmp_chpl10, ret_to_arg_ref_tmp__chpl2);
      call_tmp_chpl17 = ret_tmp_chpl2;
      doiBulkTransferStride2(ret_chpl6, i_b_chpl5, &ret_tmp_chpl2);
      chpl__autoDestroy5(&call_tmp_chpl17);
    } else {
      i__e1_x_chpl = call_tmp_chpl4;
      this_x1_chpl = *(i__e1_x_chpl);
      chpl_gen_comm_get(((void*)(&this_x2_chpl)), chpl_nodeFromLocaleID(&((i_b_chpl2).locale), INT64(0), INT32(0)), (i_b_chpl2).addr, sizeof(_array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(3), INT64(1), INT64(55));
      *(chpl__iterLF + INT64(0)) = this_x1_chpl;
      *(chpl__iterLF + INT64(1)) = this_x2_chpl;
      call_tmp_chpl18 = *(chpl__iterLF + INT64(0));
      ret_chpl7 = (&call_tmp_chpl18)->_instance;
      default_argtasksPerLocale_chpl = local_dataParTasksPerLocale_chpl;
      default_argignoreRunning_chpl = local_dataParIgnoreRunningTasks_chpl;
      default_argminIndicesPerTask_chpl = local_dataParMinGranularity_chpl;
      this_chpl6 = ret_chpl7;
      chpl_macro_tmp_5590.locale = (&this_chpl6)->locale;
      chpl_macro_tmp_5590.addr = &(((&this_chpl6)->addr)->dom);
      chpl_gen_comm_get(((void*)(&coerce_tmp_chpl3)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5590).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5590).addr, sizeof(chpl____wide_DefaultRectangularDom_1_int64_t_F), -1, COMMID(4), INT64(1), INT64(55));
      ret_to_arg_ref_tmp__chpl3 = &ret_tmp_chpl3;
      createTuple_chpl(INT64(0), ret_to_arg_ref_tmp__chpl3);
      call_tmp_x1_chpl = *(ret_tmp_chpl3 + INT64(0));
      _autoCopy_tmp__chpl = chpl_rt_buildLocaleID(chpl_nodeID, local_c_sublocid_any_chpl);
      call_tmp_chpl19 = chpl_localeID_to_locale(&_autoCopy_tmp__chpl);
      chpl_macro_tmp_5591.locale = (&call_tmp_chpl19)->locale;
      chpl_macro_tmp_5591.addr = &(((object)((&call_tmp_chpl19)->addr))->chpl__cid);
      chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5592)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5591).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5591).addr, sizeof(int32_t), -1, COMMID(5), INT64(1), INT64(55));
      ((int64_t(*)(chpl____wide_locale))chpl_vmtable[((INT64(9) * chpl_macro_tmp_5592) + INT64(3))])(call_tmp_chpl19);
      call_tmp_chpl20 = (default_argtasksPerLocale_chpl == INT64(0));
      if (call_tmp_chpl20) {
        _autoCopy_tmp__chpl2 = chpl_rt_buildLocaleID(chpl_nodeID, local_c_sublocid_any_chpl);
        call_tmp_chpl22 = chpl_localeID_to_locale(&_autoCopy_tmp__chpl2);
        call_tmp_chpl21 = call_tmp_chpl22;
        chpl_macro_tmp_5593.locale = (&call_tmp_chpl21)->locale;
        chpl_macro_tmp_5593.addr = &(((&call_tmp_chpl21)->addr)->maxTaskPar);
        chpl_gen_comm_get(((void*)(&tmp_chpl11)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5593).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5593).addr, sizeof(int64_t), -1, COMMID(6), INT64(1), INT64(55));
        ret_chpl8 = tmp_chpl11;
        goto _end__if_fn79_chpl;
      } else {
        ret_chpl8 = default_argtasksPerLocale_chpl;
        goto _end__if_fn79_chpl;
      }
      _end__if_fn79_chpl:;
      this_chpl7 = coerce_tmp_chpl3;
      call_tmp_chpl23 = chpl_task_getSerial();
      if (call_tmp_chpl23) {
        ret_x1_chpl = INT64(1);
        ret_x2_chpl = INT64(-1);
        goto _end__if_fn80_chpl;
      } else {
        chpl_macro_tmp_5594.locale = (&this_chpl7)->locale;
        chpl_macro_tmp_5594.addr = &(((&this_chpl7)->addr)->ranges);
        call_tmp_chpl24 = chpl_macro_tmp_5594;
        i_ranges_chpl = call_tmp_chpl24;
        ret_to_arg_ref_tmp__chpl4 = &ret_tmp_chpl4;
        _computeChunkStuff_chpl(ret_chpl8, default_argignoreRunning_chpl, default_argminIndicesPerTask_chpl, i_ranges_chpl, ret_to_arg_ref_tmp__chpl4);
        ret_x1_chpl = *(ret_tmp_chpl4 + INT64(0));
        ret_x2_chpl = *(ret_tmp_chpl4 + INT64(1));
        goto _end__if_fn80_chpl;
      }
      _end__if_fn80_chpl:;
      numChunks_chpl = ret_x1_chpl;
      parDim_chpl = ret_x2_chpl;
      call_tmp_chpl25 = (ret_x1_chpl == INT64(1));
      if (call_tmp_chpl25) {
        ret_to_arg_ref_tmp__chpl5 = &ret_tmp_chpl5;
        chpl_build_low_bounded_range(call_tmp_x1_chpl, ret_to_arg_ref_tmp__chpl5);
        this_chpl8 = coerce_tmp_chpl3;
        chpl_macro_tmp_5595.locale = (&this_chpl8)->locale;
        chpl_macro_tmp_5595.addr = &(((&this_chpl8)->addr)->ranges);
        call_tmp_chpl27 = chpl_macro_tmp_5595;
        chpl_macro_tmp_5596.locale = (call_tmp_chpl27).locale;
        chpl_macro_tmp_5596.addr = (*((call_tmp_chpl27).addr) + INT64(0));
        call_tmp_chpl26 = chpl_macro_tmp_5596;
        call_tmp_chpl28 = length2(call_tmp_chpl26);
        ret_to_arg_ref_tmp__chpl6 = &ret_tmp_chpl6;
        chpl___POUND_(&ret_tmp_chpl5, call_tmp_chpl28, ret_to_arg_ref_tmp__chpl6);
        call_tmp_chpl29 = *(chpl__iterLF + INT64(0));
        ret_chpl9 = (&call_tmp_chpl29)->_instance;
        call_tmp_chpl30 = *(chpl__iterLF + INT64(1));
        ret_chpl10 = (&call_tmp_chpl30)->_instance;
        _ic__F0_this_chpl = ret_chpl9;
        _ic__F0_this_chpl2 = ret_chpl10;
        tmp_chpl12 = ret_chpl9;
        chpl_macro_tmp_5597.locale = (&tmp_chpl12)->locale;
        chpl_macro_tmp_5597.addr = &(((&tmp_chpl12)->addr)->dom);
        chpl_gen_comm_get(((void*)(&coerce_tmp_chpl4)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5597).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5597).addr, sizeof(chpl____wide_DefaultRectangularDom_1_int64_t_F), -1, COMMID(7), INT64(1), INT64(55));
        ret_to_arg_ref_tmp__chpl8 = &ret_tmp_chpl8;
        createTuple_chpl(INT64(0), ret_to_arg_ref_tmp__chpl8);
        ret_to_arg_ref_tmp__chpl9 = &ret_tmp_chpl9;
        range(INT64(1), INT64(0), INT64(1), INT64(0), UINT8(false), ret_to_arg_ref_tmp__chpl9);
        *(_ic__F7_block_chpl + INT64(0)) = ret_tmp_chpl9;
        tmp_chpl13 = &_ic__F7_block_chpl;
        this_chpl9 = coerce_tmp_chpl4;
        chpl_macro_tmp_5598.locale = (&this_chpl9)->locale;
        chpl_macro_tmp_5598.addr = &(((&this_chpl9)->addr)->ranges);
        call_tmp_chpl33 = chpl_macro_tmp_5598;
        chpl_macro_tmp_5599.locale = (call_tmp_chpl33).locale;
        chpl_macro_tmp_5599.addr = (*((call_tmp_chpl33).addr) + INT64(0));
        call_tmp_chpl31 = chpl_macro_tmp_5599;
        chpl_macro_tmp_5600.locale = (call_tmp_chpl31).locale;
        chpl_macro_tmp_5600.addr = &(((call_tmp_chpl31).addr)->_low);
        chpl_gen_comm_get(((void*)(&tmp_chpl14)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5600).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5600).addr, sizeof(int64_t), -1, COMMID(8), INT64(1), INT64(55));
        followThis_x1_chpl = ret_tmp_chpl6;
        ret_chpl11 = (&followThis_x1_chpl)->_low;
        this_chpl10 = coerce_tmp_chpl4;
        chpl_macro_tmp_5601.locale = (&this_chpl10)->locale;
        chpl_macro_tmp_5601.addr = &(((&this_chpl10)->addr)->ranges);
        call_tmp_chpl34 = chpl_macro_tmp_5601;
        chpl_macro_tmp_5602.locale = (call_tmp_chpl34).locale;
        chpl_macro_tmp_5602.addr = (*((call_tmp_chpl34).addr) + INT64(0));
        call_tmp_chpl32 = chpl_macro_tmp_5602;
        chpl_macro_tmp_5603.locale = (call_tmp_chpl32).locale;
        chpl_macro_tmp_5603.addr = &(((call_tmp_chpl32).addr)->_low);
        chpl_gen_comm_get(((void*)(&tmp_chpl15)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5603).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5603).addr, sizeof(int64_t), -1, COMMID(9), INT64(1), INT64(55));
        followThis_x1_chpl2 = ret_tmp_chpl6;
        ret_to_arg_ref_tmp__chpl7 = &ret_tmp_chpl7;
        chpl_build_bounded_range(((int64_t)((tmp_chpl14 + ret_chpl11))), ((int64_t)((tmp_chpl15 + (&followThis_x1_chpl2)->_high))), ret_to_arg_ref_tmp__chpl7);
        *(*(tmp_chpl13) + INT64(0)) = ret_tmp_chpl7;
        i_x_chpl = (_ic__F7_block_chpl + INT64(0));
        tmp_chpl16 = *(i_x_chpl);
        _ic__F0_this_chpl3 = tmp_chpl16;
        ret_chpl12 = (&_ic__F0_this_chpl3)->_low;
        _ic__F10_end_chpl = (&_ic__F0_this_chpl3)->_high;
        tmp_chpl17 = ret_chpl10;
        chpl_macro_tmp_5604.locale = (&tmp_chpl17)->locale;
        chpl_macro_tmp_5604.addr = &(((&tmp_chpl17)->addr)->dom);
        chpl_gen_comm_get(((void*)(&coerce_tmp_chpl5)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5604).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5604).addr, sizeof(chpl____wide_DefaultRectangularDom_1_int64_t_F), -1, COMMID(10), INT64(1), INT64(55));
        ret_to_arg_ref_tmp__chpl11 = &ret_tmp_chpl11;
        createTuple_chpl(INT64(0), ret_to_arg_ref_tmp__chpl11);
        ret_to_arg_ref_tmp__chpl12 = &ret_tmp_chpl12;
        range(INT64(1), INT64(0), INT64(1), INT64(0), UINT8(false), ret_to_arg_ref_tmp__chpl12);
        *(_ic__F7_block_chpl2 + INT64(0)) = ret_tmp_chpl12;
        tmp_chpl18 = &_ic__F7_block_chpl2;
        this_chpl11 = coerce_tmp_chpl5;
        chpl_macro_tmp_5605.locale = (&this_chpl11)->locale;
        chpl_macro_tmp_5605.addr = &(((&this_chpl11)->addr)->ranges);
        call_tmp_chpl37 = chpl_macro_tmp_5605;
        chpl_macro_tmp_5606.locale = (call_tmp_chpl37).locale;
        chpl_macro_tmp_5606.addr = (*((call_tmp_chpl37).addr) + INT64(0));
        call_tmp_chpl35 = chpl_macro_tmp_5606;
        chpl_macro_tmp_5607.locale = (call_tmp_chpl35).locale;
        chpl_macro_tmp_5607.addr = &(((call_tmp_chpl35).addr)->_low);
        chpl_gen_comm_get(((void*)(&tmp_chpl19)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5607).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5607).addr, sizeof(int64_t), -1, COMMID(11), INT64(1), INT64(55));
        followThis_x1_chpl3 = ret_tmp_chpl6;
        this_chpl12 = coerce_tmp_chpl5;
        chpl_macro_tmp_5608.locale = (&this_chpl12)->locale;
        chpl_macro_tmp_5608.addr = &(((&this_chpl12)->addr)->ranges);
        call_tmp_chpl38 = chpl_macro_tmp_5608;
        chpl_macro_tmp_5609.locale = (call_tmp_chpl38).locale;
        chpl_macro_tmp_5609.addr = (*((call_tmp_chpl38).addr) + INT64(0));
        call_tmp_chpl36 = chpl_macro_tmp_5609;
        chpl_macro_tmp_5610.locale = (call_tmp_chpl36).locale;
        chpl_macro_tmp_5610.addr = &(((call_tmp_chpl36).addr)->_low);
        chpl_gen_comm_get(((void*)(&tmp_chpl20)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5610).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5610).addr, sizeof(int64_t), -1, COMMID(12), INT64(1), INT64(55));
        followThis_x1_chpl4 = ret_tmp_chpl6;
        ret_to_arg_ref_tmp__chpl10 = &ret_tmp_chpl10;
        chpl_build_bounded_range(((int64_t)((tmp_chpl19 + (&followThis_x1_chpl3)->_low))), ((int64_t)((tmp_chpl20 + (&followThis_x1_chpl4)->_high))), ret_to_arg_ref_tmp__chpl10);
        *(*(tmp_chpl18) + INT64(0)) = ret_tmp_chpl10;
        i_x_chpl2 = (_ic__F7_block_chpl2 + INT64(0));
        tmp_chpl21 = *(i_x_chpl2);
        _ic__F0_this_chpl4 = tmp_chpl21;
        tmp_chpl22 = _ic__F0_this_chpl2;
        chpl_macro_tmp_5611.locale = (&tmp_chpl22)->locale;
        chpl_macro_tmp_5611.addr = &(((&tmp_chpl22)->addr)->shiftedData);
        chpl_gen_comm_get(((void*)(&coerce_tmp_chpl6)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5611).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5611).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(13), INT64(1), INT64(55));
        tmp_chpl23 = _ic__F0_this_chpl;
        chpl_macro_tmp_5612.locale = (&tmp_chpl23)->locale;
        chpl_macro_tmp_5612.addr = &(((&tmp_chpl23)->addr)->shiftedData);
        chpl_gen_comm_get(((void*)(&coerce_tmp_chpl7)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5612).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5612).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(14), INT64(1), INT64(55));
        for (_ic__F9_i_chpl = ret_chpl12,_ic__F9_i_chpl2 = (&_ic__F0_this_chpl4)->_low; (tmp_chpl24 = (_ic__F9_i_chpl <= _ic__F10_end_chpl),tmp_chpl24); tmp_chpl25 = _ic__F9_i_chpl,tmp_chpl25 += INT64(1),_ic__F9_i_chpl = tmp_chpl25,tmp_chpl26 = _ic__F9_i_chpl2,tmp_chpl26 += INT64(1),_ic__F9_i_chpl2 = tmp_chpl26) {
          chpl_macro_tmp_5613.locale = (&coerce_tmp_chpl6)->locale;
          chpl_macro_tmp_5613.addr = ((&coerce_tmp_chpl6)->addr + _ic__F9_i_chpl2);
          call_tmp_chpl39 = chpl_macro_tmp_5613;
          chpl_macro_tmp_5614.locale = (&coerce_tmp_chpl7)->locale;
          chpl_macro_tmp_5614.addr = ((&coerce_tmp_chpl7)->addr + _ic__F9_i_chpl);
          call_tmp_chpl40 = chpl_macro_tmp_5614;
          chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5615)), chpl_nodeFromLocaleID(&((call_tmp_chpl39).locale), INT64(0), INT32(0)), (call_tmp_chpl39).addr, sizeof(uint64_t), -1, COMMID(15), INT64(1), INT64(55));
          chpl_gen_comm_put(((void*)(&chpl_macro_tmp_5615)), chpl_nodeFromLocaleID(&((call_tmp_chpl40).locale), INT64(0), INT32(0)), (call_tmp_chpl40).addr, sizeof(uint64_t), -1, COMMID(16), INT64(1), INT64(55));
        }
      } else {
        ret_to_arg_ref_tmp__chpl13 = &ret_tmp_chpl13;
        range(INT64(1), INT64(0), INT64(1), INT64(0), UINT8(false), ret_to_arg_ref_tmp__chpl13);
        *(locBlock_chpl + INT64(0)) = ret_tmp_chpl13;
        ret_to_arg_ref_tmp__chpl14 = &ret_tmp_chpl14;
        chpl_build_low_bounded_range(call_tmp_x1_chpl, ret_to_arg_ref_tmp__chpl14);
        this_chpl13 = coerce_tmp_chpl3;
        chpl_macro_tmp_5616.locale = (&this_chpl13)->locale;
        chpl_macro_tmp_5616.addr = &(((&this_chpl13)->addr)->ranges);
        call_tmp_chpl42 = chpl_macro_tmp_5616;
        chpl_macro_tmp_5617.locale = (call_tmp_chpl42).locale;
        chpl_macro_tmp_5617.addr = (*((call_tmp_chpl42).addr) + INT64(0));
        call_tmp_chpl41 = chpl_macro_tmp_5617;
        call_tmp_chpl43 = length2(call_tmp_chpl41);
        ret_to_arg_ref_tmp__chpl15 = &ret_tmp_chpl15;
        chpl___POUND_(&ret_tmp_chpl14, call_tmp_chpl43, ret_to_arg_ref_tmp__chpl15);
        *(locBlock_chpl + INT64(0)) = ret_tmp_chpl15;
        ret_to_arg_ref_tmp__chpl16 = &ret_tmp_chpl16;
        chpl_build_low_bounded_range(INT64(0), ret_to_arg_ref_tmp__chpl16);
        ret_to_arg_ref_tmp__chpl17 = &ret_tmp_chpl17;
        chpl___POUND_(&ret_tmp_chpl16, ret_x1_chpl, ret_to_arg_ref_tmp__chpl17);
        tmpIter_chpl = ret_tmp_chpl17;
        cast_tmp_chpl = chpl_here_alloc(sizeof(chpl_chpl___EndCount_atomic_int64_int64_t_object), INT16(2));
        this_chpl14 = ((chpl___EndCount_atomic_int64_int64_t)(cast_tmp_chpl));
        ((object)(this_chpl14))->chpl__cid = chpl__cid_chpl___EndCount_atomic_int64_int64_t;
        (this_chpl14)->i = _init_class_tmp__chpl;
        (this_chpl14)->taskCnt = INT64(0);
        (this_chpl14)->taskList = NULL;
        ret_chpl13 = type_tmp_chpl;
        _ref_tmp__chpl3 = &ret_chpl13;
        atomic_init_int_least64_t(_ref_tmp__chpl3, INT64(0));
        (&this_chpl15)->_v = ret_chpl13;
        ret_to_arg_ref_tmp__chpl18 = &ret_tmp_chpl18;
        _construct_atomic_int64(ret_chpl13, &this_chpl15, ret_to_arg_ref_tmp__chpl18);
        (this_chpl14)->i = ret_tmp_chpl18;
        (this_chpl14)->taskCnt = INT64(0);
        call_tmp_chpl44 = ((c_void_ptr)(nil));
        (this_chpl14)->taskList = call_tmp_chpl44;
        wrap_call_tmp_chpl = _construct__EndCount(&ret_tmp_chpl18, INT64(0), call_tmp_chpl44, this_chpl14);
        _coforallCount_chpl = wrap_call_tmp_chpl;
        _ref_tmp__chpl4 = &tmpIter_chpl;
        chpl_macro_tmp_5618.locale = chpl_gen_getLocaleID();
        chpl_macro_tmp_5618.addr = _ref_tmp__chpl4;
        tmp_chpl27 = chpl_macro_tmp_5618;
        call_tmp_chpl45 = length2(tmp_chpl27);
        numTasks_chpl = call_tmp_chpl45;
        _upEndCount3(_coforallCount_chpl, call_tmp_chpl45);
        _ic__F0_this_chpl5 = tmpIter_chpl;
        end_chpl = (&_ic__F0_this_chpl5)->_high;
        for (i_chpl = (&_ic__F0_this_chpl5)->_low; ((i_chpl <= end_chpl)); i_chpl += INT64(1)) {
          _args_forcoforall_fn_chpl = ((_class_localscoforall_fn6)(&chpl_macro_tmp_5619));
          *((_args_forcoforall_fn_chpl)->_0_locBlock + INT64(0)) = *(locBlock_chpl + INT64(0));
          (_args_forcoforall_fn_chpl)->_1_parDim = parDim_chpl;
          (_args_forcoforall_fn_chpl)->_2_numChunks = numChunks_chpl;
          (_args_forcoforall_fn_chpl)->_3__yieldedIndex = i_chpl;
          (_args_forcoforall_fn_chpl)->_4__coforallCount = _coforallCount_chpl;
          tmp_chpl28 = &chpl__iterLF;
          (_args_forcoforall_fn_chpl)->_5_tmp = tmp_chpl28;
          _args_vforcoforall_fn_chpl = ((void*)(_args_forcoforall_fn_chpl));
          _taskListNodecoforall_fn_chpl = chpl_nodeID;
          /*** wrapcoforall_fn2 ***/ chpl_taskListAddCoStmt(INT32(-2), INT64(131), ((chpl_task_bundle_p)(_args_vforcoforall_fn_chpl)), sizeof(chpl__class_localscoforall_fn6_object), &((_coforallCount_chpl)->taskList), _taskListNodecoforall_fn_chpl, INT64(3493), INT32(28));
        }
        _waitEndCount3(_coforallCount_chpl, numTasks_chpl);
        _field_destructor_tmp__chpl = &((_coforallCount_chpl)->i);
        call_tmp_chpl46 = &((_field_destructor_tmp__chpl)->_v);
        atomic_destroy_int_least64_t(call_tmp_chpl46);
        call_tmp_chpl47 = chpl_gen_getLocaleID();
        rvfDerefTmp_chpl = _coforallCount_chpl;
        isdirect_chpl = chpl_doDirectExecuteOn(&call_tmp_chpl47);
        if (isdirect_chpl) {
          chpl_macro_tmp_5620.locale = chpl_gen_getLocaleID();
          chpl_macro_tmp_5620.addr = rvfDerefTmp_chpl;
          tmp_chpl29 = chpl_macro_tmp_5620;
          on_fn123(tmp_chpl29);
        } else {
          _args_foron_fn_chpl = ((_class_localson_fn104)(&chpl_macro_tmp_5621));
          (_args_foron_fn_chpl)->_0_rvfDerefTmp = call_tmp_chpl47;
          chpl_macro_tmp_5622.locale = chpl_gen_getLocaleID();
          chpl_macro_tmp_5622.addr = rvfDerefTmp_chpl;
          tmp_chpl30 = chpl_macro_tmp_5622;
          (_args_foron_fn_chpl)->_1_rvfDerefTmp = tmp_chpl30;
          _args_vforon_fn_chpl = ((void*)(_args_foron_fn_chpl));
          /*** wrapon_fn131 ***/ chpl_executeOn(&call_tmp_chpl47, INT32(196), ((chpl_comm_on_bundle_p)(_args_vforon_fn_chpl)), sizeof(chpl__class_localson_fn104_object), INT64(1227), INT32(2));
        }
      }
    }
  }
  _end__ASSIGN__chpl:;
  return;
}

/* Bitmap.chpl:6 */
static void clear_chpl(chpl____wide__ref_Bitmap this_chpl6,
                       uint64_t idx_chpl) {
  uint64_t _nBits_chpl;
  chpl____wide__ref__syncvar_uint64_t call_tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t i_sv_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  uint64_t call_tmp_chpl2;
  int64_t call_tmp_chpl3;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  uint64_t call_tmp_chpl7;
  int64_t call_tmp_chpl8;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl10 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl11 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t call_tmp_chpl12 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5623;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5624;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5625;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5626;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5627;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5628;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5629;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5630;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5631;
  uint64_t chpl_macro_tmp_5632;
  uint64_t chpl_macro_tmp_5633;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5634;
  chpl_macro_tmp_5623.locale = (this_chpl6).locale;
  chpl_macro_tmp_5623.addr = &(((this_chpl6).addr)->nBits_DOLLAR__chpl);
  call_tmp_chpl = chpl_macro_tmp_5623;
  i_sv_chpl = call_tmp_chpl;
  _nBits_chpl = chpl__initCopy12(i_sv_chpl);
  call_tmp_chpl2 = (idx_chpl / UINT64(64));
  call_tmp_chpl3 = ((int64_t)(call_tmp_chpl2));
  chpl_macro_tmp_5624.locale = (this_chpl6).locale;
  chpl_macro_tmp_5624.addr = &(((this_chpl6).addr)->bitmap_chpl);
  call_tmp_chpl4 = chpl_macro_tmp_5624;
  chpl_macro_tmp_5625.locale = (call_tmp_chpl4).locale;
  chpl_macro_tmp_5625.addr = &(((call_tmp_chpl4).addr)->_instance);
  chpl_gen_comm_get(((void*)(&ret_chpl)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5625).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5625).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(17), INT64(8), INT64(55));
  call_tmp_chpl5 = ret_chpl;
  chpl_macro_tmp_5626.locale = (&call_tmp_chpl5)->locale;
  chpl_macro_tmp_5626.addr = &(((&call_tmp_chpl5)->addr)->shiftedData);
  chpl_gen_comm_get(((void*)(&coerce_tmp_chpl)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5626).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5626).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(18), INT64(8), INT64(55));
  chpl_macro_tmp_5627.locale = (&coerce_tmp_chpl)->locale;
  chpl_macro_tmp_5627.addr = ((&coerce_tmp_chpl)->addr + call_tmp_chpl3);
  call_tmp_chpl6 = chpl_macro_tmp_5627;
  call_tmp_chpl7 = (idx_chpl / UINT64(64));
  call_tmp_chpl8 = ((int64_t)(call_tmp_chpl7));
  chpl_macro_tmp_5628.locale = (this_chpl6).locale;
  chpl_macro_tmp_5628.addr = &(((this_chpl6).addr)->bitmap_chpl);
  call_tmp_chpl9 = chpl_macro_tmp_5628;
  chpl_macro_tmp_5629.locale = (call_tmp_chpl9).locale;
  chpl_macro_tmp_5629.addr = &(((call_tmp_chpl9).addr)->_instance);
  chpl_gen_comm_get(((void*)(&ret_chpl2)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5629).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5629).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(19), INT64(8), INT64(55));
  call_tmp_chpl10 = ret_chpl2;
  chpl_macro_tmp_5630.locale = (&call_tmp_chpl10)->locale;
  chpl_macro_tmp_5630.addr = &(((&call_tmp_chpl10)->addr)->shiftedData);
  chpl_gen_comm_get(((void*)(&coerce_tmp_chpl2)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5630).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5630).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(20), INT64(8), INT64(55));
  chpl_macro_tmp_5631.locale = (&coerce_tmp_chpl2)->locale;
  chpl_macro_tmp_5631.addr = ((&coerce_tmp_chpl2)->addr + call_tmp_chpl8);
  call_tmp_chpl11 = chpl_macro_tmp_5631;
  chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5632)), chpl_nodeFromLocaleID(&((call_tmp_chpl11).locale), INT64(0), INT32(0)), (call_tmp_chpl11).addr, sizeof(uint64_t), -1, COMMID(21), INT64(8), INT64(55));
  chpl_macro_tmp_5633 = (chpl_macro_tmp_5632 & ((uint64_t)(((int64_t)((~ ((int64_t)((INT64(1) << ((int64_t)((((int64_t)((((int64_t)(idx_chpl)) - INT64(1)))) % INT64(64)))))))))))));
  chpl_gen_comm_put(((void*)(&chpl_macro_tmp_5633)), chpl_nodeFromLocaleID(&((call_tmp_chpl6).locale), INT64(0), INT32(0)), (call_tmp_chpl6).addr, sizeof(uint64_t), -1, COMMID(22), INT64(8), INT64(55));
  chpl_macro_tmp_5634.locale = (this_chpl6).locale;
  chpl_macro_tmp_5634.addr = &(((this_chpl6).addr)->nBits_DOLLAR__chpl);
  call_tmp_chpl12 = chpl_macro_tmp_5634;
  chpl___ASSIGN_7(call_tmp_chpl12, _nBits_chpl);
  return;
}

/* Bitmap.chpl:17 */
static int64_t next_chpl(chpl____wide__ref_Bitmap this_chpl6) {
  string local__str_literal_1990_chpl;
  int64_t ret_chpl;
  uint64_t _nBits_chpl;
  chpl____wide__ref__syncvar_uint64_t call_tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t i_sv_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t startBit_chpl;
  chpl_bool tmp_chpl;
  int64_t call_tmp_chpl2;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl6;
  chpl_bool ret_chpl3;
  chpl_bool call_tmp_chpl7;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  uint64_t call_tmp_chpl9;
  range_int64_t_bounded_F ret_tmp_chpl;
  _ref_range_int64_t_bounded_F ret_to_arg_ref_tmp__chpl = NULL;
  _domain_DefaultRectangularDom_1_int64_t_F call_tmp_chpl10;
  _domain_DefaultRectangularDom_1_int64_t_F ret_tmp_chpl2;
  _ref__domain_DefaultRectangularDom_1_int64_t_F ret_to_arg_ref_tmp__chpl2 = NULL;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl11;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl12 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl13 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl14 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl15;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl16 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl17 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl18 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t call_tmp_chpl19 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl20;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl21 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl22 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl23 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t _ic__F1_high_chpl;
  int64_t i_chpl;
  int64_t call_tmp_chpl24;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl25 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl26 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl27 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl28;
  int64_t call_tmp_chpl29;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl30 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl31 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl32 = {CHPL_LOCALEID_T_INIT, NULL};
  int64_t call_tmp_chpl33;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl34 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl35 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t ret_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ddata_uint64_t coerce_tmp_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_uint64_t call_tmp_chpl36 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t call_tmp_chpl37 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t call_tmp_chpl38 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t i__e2_args_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5635;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5636;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5637;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5638;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5639;
  uint64_t chpl_macro_tmp_5640;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5641;
  chpl____wide__ref__domain_DefaultRectangularDom_1_int64_t_F chpl_macro_tmp_5642;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5643;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5644;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5645;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5646;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5647;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5648;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5649;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5650;
  uint64_t chpl_macro_tmp_5651;
  uint64_t chpl_macro_tmp_5652;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5653;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5654;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5655;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5656;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5657;
  uint64_t chpl_macro_tmp_5658;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5659;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5660;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5661;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5662;
  uint64_t chpl_macro_tmp_5663;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5664;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5665;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5666;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5667;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5668;
  chpl____wide__ref__wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5669;
  chpl____wide__ref__wide__ddata_uint64_t chpl_macro_tmp_5670;
  chpl____wide__ref_uint64_t chpl_macro_tmp_5671;
  uint64_t chpl_macro_tmp_5672;
  uint64_t chpl_macro_tmp_5673;
  chpl____wide__ref__syncvar_uint64_t chpl_macro_tmp_5674;
  chpl____wide__ref__wide__array_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t chpl_macro_tmp_5675;
  local__str_literal_1990_chpl /* "A bit was not found!!! Bitmap: " */ = _str_literal_1990 /* "A bit was not found!!! Bitmap: " */;
  chpl_macro_tmp_5635.locale = (this_chpl6).locale;
  chpl_macro_tmp_5635.addr = &(((this_chpl6).addr)->nBits_DOLLAR__chpl);
  call_tmp_chpl = chpl_macro_tmp_5635;
  i_sv_chpl = call_tmp_chpl;
  _nBits_chpl = chpl__initCopy12(i_sv_chpl);
  startBit_chpl = INT64(0);
  call_tmp_chpl2 = (INT64(0) / INT64(64));
  chpl_macro_tmp_5636.locale = (this_chpl6).locale;
  chpl_macro_tmp_5636.addr = &(((this_chpl6).addr)->bitmap_chpl);
  call_tmp_chpl3 = chpl_macro_tmp_5636;
  chpl_macro_tmp_5637.locale = (call_tmp_chpl3).locale;
  chpl_macro_tmp_5637.addr = &(((call_tmp_chpl3).addr)->_instance);
  chpl_gen_comm_get(((void*)(&ret_chpl2)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5637).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5637).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(23), INT64(22), INT64(55));
  call_tmp_chpl4 = ret_chpl2;
  chpl_macro_tmp_5638.locale = (&call_tmp_chpl4)->locale;
  chpl_macro_tmp_5638.addr = &(((&call_tmp_chpl4)->addr)->shiftedData);
  chpl_gen_comm_get(((void*)(&coerce_tmp_chpl)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5638).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5638).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(24), INT64(22), INT64(55));
  chpl_macro_tmp_5639.locale = (&coerce_tmp_chpl)->locale;
  chpl_macro_tmp_5639.addr = ((&coerce_tmp_chpl)->addr + call_tmp_chpl2);
  call_tmp_chpl5 = chpl_macro_tmp_5639;
  chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5640)), chpl_nodeFromLocaleID(&((call_tmp_chpl5).locale), INT64(0), INT32(0)), (call_tmp_chpl5).addr, sizeof(uint64_t), -1, COMMID(25), INT64(22), INT64(55));
  tmp_chpl = (chpl_macro_tmp_5640 == UINT64(18446744073709551615));
  while (tmp_chpl) {
    call_tmp_chpl6 = (startBit_chpl + INT64(64));
    startBit_chpl = call_tmp_chpl6;
    call_tmp_chpl7 = (! (call_tmp_chpl6 < INT64(0)));
    if (call_tmp_chpl7) {
      ret_chpl3 = (((uint64_t)(call_tmp_chpl6)) >= _nBits_chpl);
      goto _end__if_fn235_chpl;
    } else {
      ret_chpl3 = UINT8(false);
      goto _end__if_fn235_chpl;
    }
    _end__if_fn235_chpl:;
    if (ret_chpl3) {
      chpl_macro_tmp_5641.locale = (this_chpl6).locale;
      chpl_macro_tmp_5641.addr = &(((this_chpl6).addr)->bitmapSpace_chpl);
      call_tmp_chpl8 = chpl_macro_tmp_5641;
      call_tmp_chpl9 = (((uint64_t)((_nBits_chpl - UINT64(1)))) / UINT64(64));
      ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
      chpl_build_bounded_range(INT64(0), ((int64_t)(call_tmp_chpl9)), ret_to_arg_ref_tmp__chpl);
      ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
      chpl__buildDomainExpr2(&ret_tmp_chpl, ret_to_arg_ref_tmp__chpl2);
      call_tmp_chpl10 = ret_tmp_chpl2;
      chpl_macro_tmp_5642.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_5642.addr = &ret_tmp_chpl2;
      tmp_chpl2 = chpl_macro_tmp_5642;
      chpl___ASSIGN_3(call_tmp_chpl8, tmp_chpl2);
      chpl__autoDestroy5(&call_tmp_chpl10);
      call_tmp_chpl11 = (call_tmp_chpl6 / INT64(64));
      chpl_macro_tmp_5643.locale = (this_chpl6).locale;
      chpl_macro_tmp_5643.addr = &(((this_chpl6).addr)->bitmap_chpl);
      call_tmp_chpl12 = chpl_macro_tmp_5643;
      chpl_macro_tmp_5644.locale = (call_tmp_chpl12).locale;
      chpl_macro_tmp_5644.addr = &(((call_tmp_chpl12).addr)->_instance);
      chpl_gen_comm_get(((void*)(&ret_chpl4)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5644).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5644).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(26), INT64(28), INT64(55));
      call_tmp_chpl13 = ret_chpl4;
      chpl_macro_tmp_5645.locale = (&call_tmp_chpl13)->locale;
      chpl_macro_tmp_5645.addr = &(((&call_tmp_chpl13)->addr)->shiftedData);
      chpl_gen_comm_get(((void*)(&coerce_tmp_chpl2)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5645).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5645).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(27), INT64(28), INT64(55));
      chpl_macro_tmp_5646.locale = (&coerce_tmp_chpl2)->locale;
      chpl_macro_tmp_5646.addr = ((&coerce_tmp_chpl2)->addr + call_tmp_chpl11);
      call_tmp_chpl14 = chpl_macro_tmp_5646;
      call_tmp_chpl15 = (call_tmp_chpl6 / INT64(64));
      chpl_macro_tmp_5647.locale = (this_chpl6).locale;
      chpl_macro_tmp_5647.addr = &(((this_chpl6).addr)->bitmap_chpl);
      call_tmp_chpl16 = chpl_macro_tmp_5647;
      chpl_macro_tmp_5648.locale = (call_tmp_chpl16).locale;
      chpl_macro_tmp_5648.addr = &(((call_tmp_chpl16).addr)->_instance);
      chpl_gen_comm_get(((void*)(&ret_chpl5)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5648).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5648).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(28), INT64(28), INT64(55));
      call_tmp_chpl17 = ret_chpl5;
      chpl_macro_tmp_5649.locale = (&call_tmp_chpl17)->locale;
      chpl_macro_tmp_5649.addr = &(((&call_tmp_chpl17)->addr)->shiftedData);
      chpl_gen_comm_get(((void*)(&coerce_tmp_chpl3)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5649).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5649).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(29), INT64(28), INT64(55));
      chpl_macro_tmp_5650.locale = (&coerce_tmp_chpl3)->locale;
      chpl_macro_tmp_5650.addr = ((&coerce_tmp_chpl3)->addr + call_tmp_chpl15);
      call_tmp_chpl18 = chpl_macro_tmp_5650;
      chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5651)), chpl_nodeFromLocaleID(&((call_tmp_chpl18).locale), INT64(0), INT32(0)), (call_tmp_chpl18).addr, sizeof(uint64_t), -1, COMMID(30), INT64(28), INT64(55));
      chpl_macro_tmp_5652 = (chpl_macro_tmp_5651 | ((uint64_t)(((int64_t)((INT64(1) << ((int64_t)((call_tmp_chpl6 % INT64(64))))))))));
      chpl_gen_comm_put(((void*)(&chpl_macro_tmp_5652)), chpl_nodeFromLocaleID(&((call_tmp_chpl14).locale), INT64(0), INT32(0)), (call_tmp_chpl14).addr, sizeof(uint64_t), -1, COMMID(31), INT64(28), INT64(55));
      chpl_macro_tmp_5653.locale = (this_chpl6).locale;
      chpl_macro_tmp_5653.addr = &(((this_chpl6).addr)->nBits_DOLLAR__chpl);
      call_tmp_chpl19 = chpl_macro_tmp_5653;
      chpl___ASSIGN_7(call_tmp_chpl19, ((uint64_t)((_nBits_chpl * UINT64(2)))));
      ret_chpl = call_tmp_chpl6;
      goto _end_next_chpl;
    }
    call_tmp_chpl20 = (call_tmp_chpl6 / INT64(64));
    chpl_macro_tmp_5654.locale = (this_chpl6).locale;
    chpl_macro_tmp_5654.addr = &(((this_chpl6).addr)->bitmap_chpl);
    call_tmp_chpl21 = chpl_macro_tmp_5654;
    chpl_macro_tmp_5655.locale = (call_tmp_chpl21).locale;
    chpl_macro_tmp_5655.addr = &(((call_tmp_chpl21).addr)->_instance);
    chpl_gen_comm_get(((void*)(&ret_chpl6)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5655).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5655).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(32), INT64(22), INT64(55));
    call_tmp_chpl22 = ret_chpl6;
    chpl_macro_tmp_5656.locale = (&call_tmp_chpl22)->locale;
    chpl_macro_tmp_5656.addr = &(((&call_tmp_chpl22)->addr)->shiftedData);
    chpl_gen_comm_get(((void*)(&coerce_tmp_chpl4)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5656).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5656).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(33), INT64(22), INT64(55));
    chpl_macro_tmp_5657.locale = (&coerce_tmp_chpl4)->locale;
    chpl_macro_tmp_5657.addr = ((&coerce_tmp_chpl4)->addr + call_tmp_chpl20);
    call_tmp_chpl23 = chpl_macro_tmp_5657;
    chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5658)), chpl_nodeFromLocaleID(&((call_tmp_chpl23).locale), INT64(0), INT32(0)), (call_tmp_chpl23).addr, sizeof(uint64_t), -1, COMMID(34), INT64(22), INT64(55));
    tmp_chpl = (chpl_macro_tmp_5658 == UINT64(18446744073709551615));
  }
  _ic__F1_high_chpl = ((int64_t)(_nBits_chpl));
  for (i_chpl = startBit_chpl; ((i_chpl <= _ic__F1_high_chpl)); i_chpl += INT64(1)) {
    call_tmp_chpl24 = (i_chpl / INT64(64));
    chpl_macro_tmp_5659.locale = (this_chpl6).locale;
    chpl_macro_tmp_5659.addr = &(((this_chpl6).addr)->bitmap_chpl);
    call_tmp_chpl25 = chpl_macro_tmp_5659;
    chpl_macro_tmp_5660.locale = (call_tmp_chpl25).locale;
    chpl_macro_tmp_5660.addr = &(((call_tmp_chpl25).addr)->_instance);
    chpl_gen_comm_get(((void*)(&ret_chpl7)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5660).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5660).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(35), INT64(36), INT64(55));
    call_tmp_chpl26 = ret_chpl7;
    chpl_macro_tmp_5661.locale = (&call_tmp_chpl26)->locale;
    chpl_macro_tmp_5661.addr = &(((&call_tmp_chpl26)->addr)->shiftedData);
    chpl_gen_comm_get(((void*)(&coerce_tmp_chpl5)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5661).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5661).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(36), INT64(36), INT64(55));
    chpl_macro_tmp_5662.locale = (&coerce_tmp_chpl5)->locale;
    chpl_macro_tmp_5662.addr = ((&coerce_tmp_chpl5)->addr + call_tmp_chpl24);
    call_tmp_chpl27 = chpl_macro_tmp_5662;
    chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5663)), chpl_nodeFromLocaleID(&((call_tmp_chpl27).locale), INT64(0), INT32(0)), (call_tmp_chpl27).addr, sizeof(uint64_t), -1, COMMID(37), INT64(36), INT64(55));
    call_tmp_chpl28 = ((chpl_macro_tmp_5663 & ((uint64_t)(((int64_t)((INT64(1) << ((int64_t)((i_chpl % INT64(64)))))))))) == UINT64(0));
    if (call_tmp_chpl28) {
      call_tmp_chpl29 = (i_chpl / INT64(64));
      chpl_macro_tmp_5664.locale = (this_chpl6).locale;
      chpl_macro_tmp_5664.addr = &(((this_chpl6).addr)->bitmap_chpl);
      call_tmp_chpl30 = chpl_macro_tmp_5664;
      chpl_macro_tmp_5665.locale = (call_tmp_chpl30).locale;
      chpl_macro_tmp_5665.addr = &(((call_tmp_chpl30).addr)->_instance);
      chpl_gen_comm_get(((void*)(&ret_chpl8)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5665).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5665).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(38), INT64(37), INT64(55));
      call_tmp_chpl31 = ret_chpl8;
      chpl_macro_tmp_5666.locale = (&call_tmp_chpl31)->locale;
      chpl_macro_tmp_5666.addr = &(((&call_tmp_chpl31)->addr)->shiftedData);
      chpl_gen_comm_get(((void*)(&coerce_tmp_chpl6)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5666).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5666).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(39), INT64(37), INT64(55));
      chpl_macro_tmp_5667.locale = (&coerce_tmp_chpl6)->locale;
      chpl_macro_tmp_5667.addr = ((&coerce_tmp_chpl6)->addr + call_tmp_chpl29);
      call_tmp_chpl32 = chpl_macro_tmp_5667;
      call_tmp_chpl33 = (i_chpl / INT64(64));
      chpl_macro_tmp_5668.locale = (this_chpl6).locale;
      chpl_macro_tmp_5668.addr = &(((this_chpl6).addr)->bitmap_chpl);
      call_tmp_chpl34 = chpl_macro_tmp_5668;
      chpl_macro_tmp_5669.locale = (call_tmp_chpl34).locale;
      chpl_macro_tmp_5669.addr = &(((call_tmp_chpl34).addr)->_instance);
      chpl_gen_comm_get(((void*)(&ret_chpl9)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5669).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5669).addr, sizeof(chpl____wide_DefaultRectangularArr_uint64_t_1_int64_t_F_int64_t), -1, COMMID(40), INT64(37), INT64(55));
      call_tmp_chpl35 = ret_chpl9;
      chpl_macro_tmp_5670.locale = (&call_tmp_chpl35)->locale;
      chpl_macro_tmp_5670.addr = &(((&call_tmp_chpl35)->addr)->shiftedData);
      chpl_gen_comm_get(((void*)(&coerce_tmp_chpl7)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_5670).locale), INT64(0), INT32(0)), (chpl_macro_tmp_5670).addr, sizeof(chpl____wide__ddata_uint64_t), -1, COMMID(41), INT64(37), INT64(55));
      chpl_macro_tmp_5671.locale = (&coerce_tmp_chpl7)->locale;
      chpl_macro_tmp_5671.addr = ((&coerce_tmp_chpl7)->addr + call_tmp_chpl33);
      call_tmp_chpl36 = chpl_macro_tmp_5671;
      chpl_gen_comm_get(((void*)(&chpl_macro_tmp_5672)), chpl_nodeFromLocaleID(&((call_tmp_chpl36).locale), INT64(0), INT32(0)), (call_tmp_chpl36).addr, sizeof(uint64_t), -1, COMMID(42), INT64(37), INT64(55));
      chpl_macro_tmp_5673 = (chpl_macro_tmp_5672 | ((uint64_t)(((int64_t)((INT64(1) << ((int64_t)((i_chpl % INT64(64))))))))));
      chpl_gen_comm_put(((void*)(&chpl_macro_tmp_5673)), chpl_nodeFromLocaleID(&((call_tmp_chpl32).locale), INT64(0), INT32(0)), (call_tmp_chpl32).addr, sizeof(uint64_t), -1, COMMID(43), INT64(37), INT64(55));
      chpl_macro_tmp_5674.locale = (this_chpl6).locale;
      chpl_macro_tmp_5674.addr = &(((this_chpl6).addr)->nBits_DOLLAR__chpl);
      call_tmp_chpl37 = chpl_macro_tmp_5674;
      chpl___ASSIGN_7(call_tmp_chpl37, _nBits_chpl);
      ret_chpl = i_chpl;
      goto _end_next_chpl;
    }
  }
  chpl_macro_tmp_5675.locale = (this_chpl6).locale;
  chpl_macro_tmp_5675.addr = &(((this_chpl6).addr)->bitmap_chpl);
  call_tmp_chpl38 = chpl_macro_tmp_5675;
  i__e2_args_chpl = call_tmp_chpl38;
  halt2(&local__str_literal_1990_chpl /* "A bit was not found!!! Bitmap: " */, i__e2_args_chpl, INT64(43), INT32(55));
  _end_next_chpl:;
  return ret_chpl;
}

