/* ChapelTuple.chpl:40 */
static void chpl__init_ChapelTuple(int64_t _ln,
                                   int32_t _fn) {
  _ref_int32_t refIndentLevel = NULL;
  if (chpl__init_ChapelTuple_p) {
    goto _exit_chpl__init_ChapelTuple;
  }
  printModuleInit("%*s\n", "ChapelTuple", INT64(11));
  refIndentLevel = &moduleInitLevel;
  *(refIndentLevel) += INT64(1);
  chpl__init_ChapelTuple_p = UINT8(true);
  *(refIndentLevel) -= INT64(1);
  _exit_chpl__init_ChapelTuple:;
  return;
}

/* ChapelTuple.chpl:162 */
static chpl____wide__ref_range_int64_t_bounded_F this10(chpl____wide__ref__tuple_1_star_range_int64_t_bounded_F this12,
                                                        int64_t i) {
  chpl____wide__ref_range_int64_t_bounded_F call_tmp2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_range_int64_t_bounded_F chpl_macro_tmp_608;
  chpl_macro_tmp_608.locale = (this12).locale;
  chpl_macro_tmp_608.addr = (*((this12).addr) + (i - INT64(1)));
  call_tmp2 = chpl_macro_tmp_608;
  return call_tmp2;
}

/* ChapelTuple.chpl:162 */
static _ref_int64_t this8(_ref__tuple_56_star_int64_t this12,
                          int64_t i) {
  _ref_int64_t call_tmp2 = NULL;
  call_tmp2 = (*(this12) + (i - INT64(1)));
  return call_tmp2;
}

/* ChapelTuple.chpl:162 */
static chpl____wide__ref_int64_t this9(chpl____wide__ref__tuple_1_star_int64_t this12,
                                       int64_t i) {
  chpl____wide__ref_int64_t call_tmp2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_int64_t chpl_macro_tmp_609;
  chpl_macro_tmp_609.locale = (this12).locale;
  chpl_macro_tmp_609.addr = (*((this12).addr) + (i - INT64(1)));
  call_tmp2 = chpl_macro_tmp_609;
  return call_tmp2;
}

/* ChapelTuple.chpl:240 */
static void readWriteThis(chpl____wide__ref__tuple_2_chpl_bool_int64_t this12,
                          _ref_channel_T_dynamic_F f) {
  string local__str_literal_411;
  string local__str_literal_587;
  string local__str_literal_585;
  string local__str_literal_583;
  string local__str_literal_581;
  int64_t local_QIO_TUPLE_FORMAT_JSON;
  string local__str_literal_579;
  string local__str_literal_400;
  string local__str_literal_577;
  int64_t local_QIO_TUPLE_FORMAT_SPACE;
  int64_t call_tmp2;
  ioLiteral_chpl start;
  ioLiteral_chpl this13;
  string _init_class_tmp_;
  string this14;
  c_ptr_uint8_t call_tmp3 = NULL;
  int32_t default_arglocale_id;
  string ret_tmp;
  _ref_string ret_to_arg_ref_tmp_ = NULL;
  ioLiteral_chpl ret_tmp2;
  _ref_ioLiteral ret_to_arg_ref_tmp_2 = NULL;
  ioLiteral_chpl comma;
  ioLiteral_chpl this15;
  string _init_class_tmp_2;
  string this16;
  c_ptr_uint8_t call_tmp4 = NULL;
  int32_t default_arglocale_id2;
  string ret_tmp3;
  _ref_string ret_to_arg_ref_tmp_3 = NULL;
  ioLiteral_chpl ret_tmp4;
  _ref_ioLiteral ret_to_arg_ref_tmp_4 = NULL;
  ioLiteral_chpl end;
  ioLiteral_chpl this17;
  string _init_class_tmp_3;
  string this18;
  c_ptr_uint8_t call_tmp5 = NULL;
  int32_t default_arglocale_id3;
  string ret_tmp5;
  _ref_string ret_to_arg_ref_tmp_5 = NULL;
  ioLiteral_chpl ret_tmp6;
  _ref_ioLiteral ret_to_arg_ref_tmp_6 = NULL;
  chpl_bool call_tmp6;
  chpl_bool call_tmp7;
  ioLiteral_chpl call_tmp8;
  ioLiteral_chpl this19;
  string _init_class_tmp_4;
  string wrap_arg;
  ioLiteral_chpl ret_tmp7;
  _ref_ioLiteral ret_to_arg_ref_tmp_7 = NULL;
  _ref_ioLiteral _ref_tmp_ = NULL;
  ioLiteral_chpl call_tmp9;
  ioLiteral_chpl this20;
  string _init_class_tmp_5;
  string wrap_arg2;
  ioLiteral_chpl ret_tmp8;
  _ref_ioLiteral ret_to_arg_ref_tmp_8 = NULL;
  _ref_ioLiteral _ref_tmp_2 = NULL;
  ioLiteral_chpl call_tmp10;
  ioLiteral_chpl this21;
  string _init_class_tmp_6;
  string wrap_arg3;
  ioLiteral_chpl ret_tmp9;
  _ref_ioLiteral ret_to_arg_ref_tmp_9 = NULL;
  _ref_ioLiteral _ref_tmp_3 = NULL;
  _ref_string _field_destructor_tmp_ = NULL;
  chpl____wide__ref_string T = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_2 = NULL;
  chpl____wide__ref_string T2 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_3 = NULL;
  chpl____wide__ref_string T3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp11;
  ioLiteral_chpl call_tmp12;
  ioLiteral_chpl this22;
  string _init_class_tmp_7;
  string wrap_arg4;
  ioLiteral_chpl ret_tmp10;
  _ref_ioLiteral ret_to_arg_ref_tmp_10 = NULL;
  _ref_ioLiteral _ref_tmp_4 = NULL;
  ioLiteral_chpl call_tmp13;
  ioLiteral_chpl this23;
  string _init_class_tmp_8;
  string wrap_arg5;
  ioLiteral_chpl ret_tmp11;
  _ref_ioLiteral ret_to_arg_ref_tmp_11 = NULL;
  _ref_ioLiteral _ref_tmp_5 = NULL;
  ioLiteral_chpl call_tmp14;
  ioLiteral_chpl this24;
  string _init_class_tmp_9;
  string wrap_arg6;
  ioLiteral_chpl ret_tmp12;
  _ref_ioLiteral ret_to_arg_ref_tmp_12 = NULL;
  _ref_ioLiteral _ref_tmp_6 = NULL;
  _ref_string _field_destructor_tmp_4 = NULL;
  chpl____wide__ref_string T4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_5 = NULL;
  chpl____wide__ref_string T5 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_6 = NULL;
  chpl____wide__ref_string T6 = {CHPL_LOCALEID_T_INIT, NULL};
  ioLiteral_chpl call_tmp15;
  ioLiteral_chpl this25;
  string _init_class_tmp_10;
  string wrap_arg7;
  ioLiteral_chpl ret_tmp13;
  _ref_ioLiteral ret_to_arg_ref_tmp_13 = NULL;
  _ref_ioLiteral _ref_tmp_7 = NULL;
  ioLiteral_chpl call_tmp16;
  ioLiteral_chpl this26;
  string _init_class_tmp_11;
  string wrap_arg8;
  ioLiteral_chpl ret_tmp14;
  _ref_ioLiteral ret_to_arg_ref_tmp_14 = NULL;
  _ref_ioLiteral _ref_tmp_8 = NULL;
  ioLiteral_chpl call_tmp17;
  ioLiteral_chpl this27;
  string _init_class_tmp_12;
  string wrap_arg9;
  ioLiteral_chpl ret_tmp15;
  _ref_ioLiteral ret_to_arg_ref_tmp_15 = NULL;
  _ref_ioLiteral _ref_tmp_9 = NULL;
  _ref_string _field_destructor_tmp_7 = NULL;
  chpl____wide__ref_string T7 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_8 = NULL;
  chpl____wide__ref_string T8 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_9 = NULL;
  chpl____wide__ref_string T9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp18;
  chpl_bool T10;
  chpl_bool call_tmp19;
  int64_t T11;
  chpl_bool call_tmp20;
  _ref_string _field_destructor_tmp_10 = NULL;
  chpl____wide__ref_string T12 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_11 = NULL;
  chpl____wide__ref_string T13 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _field_destructor_tmp_12 = NULL;
  chpl____wide__ref_string T14 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string chpl_macro_tmp_610;
  chpl____wide__ref_string chpl_macro_tmp_611;
  chpl____wide__ref_string chpl_macro_tmp_612;
  chpl____wide__ref_string chpl_macro_tmp_613;
  chpl____wide__ref_string chpl_macro_tmp_614;
  chpl____wide__ref_string chpl_macro_tmp_615;
  chpl____wide__ref_string chpl_macro_tmp_616;
  chpl____wide__ref_string chpl_macro_tmp_617;
  chpl____wide__ref_string chpl_macro_tmp_618;
  chpl____wide__ref_chpl_bool chpl_macro_tmp_619;
  chpl____wide__ref_int64_t chpl_macro_tmp_620;
  chpl____wide__ref_string chpl_macro_tmp_621;
  chpl____wide__ref_string chpl_macro_tmp_622;
  chpl____wide__ref_string chpl_macro_tmp_623;
  local__str_literal_411 /* ")" */ = _str_literal_411 /* ")" */;
  local__str_literal_587 /* "(" */ = _str_literal_587 /* "(" */;
  local__str_literal_585 /* "]" */ = _str_literal_585 /* "]" */;
  local__str_literal_583 /* ", " */ = _str_literal_583 /* ", " */;
  local__str_literal_581 /* "[" */ = _str_literal_581 /* "[" */;
  local_QIO_TUPLE_FORMAT_JSON = QIO_TUPLE_FORMAT_JSON;
  local__str_literal_579 /* "" */ = _str_literal_579 /* "" */;
  local__str_literal_400 /* " " */ = _str_literal_400 /* " " */;
  local__str_literal_577 /* "" */ = _str_literal_577 /* "" */;
  local_QIO_TUPLE_FORMAT_SPACE = QIO_TUPLE_FORMAT_SPACE;
  call_tmp2 = styleElement_chpl(f, QIO_STYLE_ELEMENT_TUPLE);
  (&_init_class_tmp_)->len = INT64(0);
  (&_init_class_tmp_)->_size = INT64(0);
  (&_init_class_tmp_)->buff = nil;
  (&_init_class_tmp_)->owned = UINT8(false);
  (&_init_class_tmp_)->locale_id = INT32(0);
  (&this13)->val_chpl = _init_class_tmp_;
  (&this13)->ignoreWhiteSpace_chpl = UINT8(false);
  (&this14)->len = INT64(0);
  (&this14)->_size = INT64(0);
  (&this14)->buff = nil;
  (&this14)->owned = UINT8(false);
  (&this14)->locale_id = INT32(0);
  (&this14)->len = INT64(0);
  (&this14)->_size = INT64(0);
  call_tmp3 = ((c_ptr_uint8_t)(nil));
  (&this14)->buff = call_tmp3;
  (&this14)->owned = UINT8(true);
  default_arglocale_id = chpl_nodeID;
  (&this14)->locale_id = default_arglocale_id;
  ret_to_arg_ref_tmp_ = &ret_tmp;
  _construct_string(INT64(0), INT64(0), call_tmp3, UINT8(true), default_arglocale_id, &this14, ret_to_arg_ref_tmp_);
  (&this13)->val_chpl = ret_tmp;
  (&this13)->ignoreWhiteSpace_chpl = UINT8(true);
  ret_to_arg_ref_tmp_2 = &ret_tmp2;
  _construct_ioLiteral_chpl(&ret_tmp, UINT8(true), &this13, ret_to_arg_ref_tmp_2);
  start = ret_tmp2;
  (&_init_class_tmp_2)->len = INT64(0);
  (&_init_class_tmp_2)->_size = INT64(0);
  (&_init_class_tmp_2)->buff = nil;
  (&_init_class_tmp_2)->owned = UINT8(false);
  (&_init_class_tmp_2)->locale_id = INT32(0);
  (&this15)->val_chpl = _init_class_tmp_2;
  (&this15)->ignoreWhiteSpace_chpl = UINT8(false);
  (&this16)->len = INT64(0);
  (&this16)->_size = INT64(0);
  (&this16)->buff = nil;
  (&this16)->owned = UINT8(false);
  (&this16)->locale_id = INT32(0);
  (&this16)->len = INT64(0);
  (&this16)->_size = INT64(0);
  call_tmp4 = ((c_ptr_uint8_t)(nil));
  (&this16)->buff = call_tmp4;
  (&this16)->owned = UINT8(true);
  default_arglocale_id2 = chpl_nodeID;
  (&this16)->locale_id = default_arglocale_id2;
  ret_to_arg_ref_tmp_3 = &ret_tmp3;
  _construct_string(INT64(0), INT64(0), call_tmp4, UINT8(true), default_arglocale_id2, &this16, ret_to_arg_ref_tmp_3);
  (&this15)->val_chpl = ret_tmp3;
  (&this15)->ignoreWhiteSpace_chpl = UINT8(true);
  ret_to_arg_ref_tmp_4 = &ret_tmp4;
  _construct_ioLiteral_chpl(&ret_tmp3, UINT8(true), &this15, ret_to_arg_ref_tmp_4);
  comma = ret_tmp4;
  (&_init_class_tmp_3)->len = INT64(0);
  (&_init_class_tmp_3)->_size = INT64(0);
  (&_init_class_tmp_3)->buff = nil;
  (&_init_class_tmp_3)->owned = UINT8(false);
  (&_init_class_tmp_3)->locale_id = INT32(0);
  (&this17)->val_chpl = _init_class_tmp_3;
  (&this17)->ignoreWhiteSpace_chpl = UINT8(false);
  (&this18)->len = INT64(0);
  (&this18)->_size = INT64(0);
  (&this18)->buff = nil;
  (&this18)->owned = UINT8(false);
  (&this18)->locale_id = INT32(0);
  (&this18)->len = INT64(0);
  (&this18)->_size = INT64(0);
  call_tmp5 = ((c_ptr_uint8_t)(nil));
  (&this18)->buff = call_tmp5;
  (&this18)->owned = UINT8(true);
  default_arglocale_id3 = chpl_nodeID;
  (&this18)->locale_id = default_arglocale_id3;
  ret_to_arg_ref_tmp_5 = &ret_tmp5;
  _construct_string(INT64(0), INT64(0), call_tmp5, UINT8(true), default_arglocale_id3, &this18, ret_to_arg_ref_tmp_5);
  (&this17)->val_chpl = ret_tmp5;
  (&this17)->ignoreWhiteSpace_chpl = UINT8(true);
  ret_to_arg_ref_tmp_6 = &ret_tmp6;
  _construct_ioLiteral_chpl(&ret_tmp5, UINT8(true), &this17, ret_to_arg_ref_tmp_6);
  end = ret_tmp6;
  call_tmp6 = binary_chpl(f);
  call_tmp7 = (call_tmp2 == local_QIO_TUPLE_FORMAT_SPACE);
  if (call_tmp7) {
    (&_init_class_tmp_4)->len = INT64(0);
    (&_init_class_tmp_4)->_size = INT64(0);
    (&_init_class_tmp_4)->buff = nil;
    (&_init_class_tmp_4)->owned = UINT8(false);
    (&_init_class_tmp_4)->locale_id = INT32(0);
    (&this19)->val_chpl = _init_class_tmp_4;
    (&this19)->ignoreWhiteSpace_chpl = UINT8(false);
    wrap_arg = chpl__autoCopy6(&local__str_literal_577 /* "" */);
    (&this19)->val_chpl = wrap_arg;
    (&this19)->ignoreWhiteSpace_chpl = UINT8(true);
    ret_to_arg_ref_tmp_7 = &ret_tmp7;
    _construct_ioLiteral_chpl(&wrap_arg, UINT8(true), &this19, ret_to_arg_ref_tmp_7);
    call_tmp8 = ret_tmp7;
    _ref_tmp_ = &start;
    chpl___ASSIGN_18(_ref_tmp_, &ret_tmp7);
    (&_init_class_tmp_5)->len = INT64(0);
    (&_init_class_tmp_5)->_size = INT64(0);
    (&_init_class_tmp_5)->buff = nil;
    (&_init_class_tmp_5)->owned = UINT8(false);
    (&_init_class_tmp_5)->locale_id = INT32(0);
    (&this20)->val_chpl = _init_class_tmp_5;
    (&this20)->ignoreWhiteSpace_chpl = UINT8(false);
    wrap_arg2 = chpl__autoCopy6(&local__str_literal_400 /* " " */);
    (&this20)->val_chpl = wrap_arg2;
    (&this20)->ignoreWhiteSpace_chpl = UINT8(true);
    ret_to_arg_ref_tmp_8 = &ret_tmp8;
    _construct_ioLiteral_chpl(&wrap_arg2, UINT8(true), &this20, ret_to_arg_ref_tmp_8);
    call_tmp9 = ret_tmp8;
    _ref_tmp_2 = &comma;
    chpl___ASSIGN_18(_ref_tmp_2, &ret_tmp8);
    (&_init_class_tmp_6)->len = INT64(0);
    (&_init_class_tmp_6)->_size = INT64(0);
    (&_init_class_tmp_6)->buff = nil;
    (&_init_class_tmp_6)->owned = UINT8(false);
    (&_init_class_tmp_6)->locale_id = INT32(0);
    (&this21)->val_chpl = _init_class_tmp_6;
    (&this21)->ignoreWhiteSpace_chpl = UINT8(false);
    wrap_arg3 = chpl__autoCopy6(&local__str_literal_579 /* "" */);
    (&this21)->val_chpl = wrap_arg3;
    (&this21)->ignoreWhiteSpace_chpl = UINT8(true);
    ret_to_arg_ref_tmp_9 = &ret_tmp9;
    _construct_ioLiteral_chpl(&wrap_arg3, UINT8(true), &this21, ret_to_arg_ref_tmp_9);
    call_tmp10 = ret_tmp9;
    _ref_tmp_3 = &end;
    chpl___ASSIGN_18(_ref_tmp_3, &ret_tmp9);
    _field_destructor_tmp_ = &((&call_tmp8)->val_chpl);
    chpl_macro_tmp_610.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_610.addr = _field_destructor_tmp_;
    T = chpl_macro_tmp_610;
    deinit44(T);
    _field_destructor_tmp_2 = &((&call_tmp9)->val_chpl);
    chpl_macro_tmp_611.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_611.addr = _field_destructor_tmp_2;
    T2 = chpl_macro_tmp_611;
    deinit44(T2);
    _field_destructor_tmp_3 = &((&call_tmp10)->val_chpl);
    chpl_macro_tmp_612.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_612.addr = _field_destructor_tmp_3;
    T3 = chpl_macro_tmp_612;
    deinit44(T3);
  } else {
    call_tmp11 = (call_tmp2 == local_QIO_TUPLE_FORMAT_JSON);
    if (call_tmp11) {
      (&_init_class_tmp_7)->len = INT64(0);
      (&_init_class_tmp_7)->_size = INT64(0);
      (&_init_class_tmp_7)->buff = nil;
      (&_init_class_tmp_7)->owned = UINT8(false);
      (&_init_class_tmp_7)->locale_id = INT32(0);
      (&this22)->val_chpl = _init_class_tmp_7;
      (&this22)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg4 = chpl__autoCopy6(&local__str_literal_581 /* "[" */);
      (&this22)->val_chpl = wrap_arg4;
      (&this22)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_10 = &ret_tmp10;
      _construct_ioLiteral_chpl(&wrap_arg4, UINT8(true), &this22, ret_to_arg_ref_tmp_10);
      call_tmp12 = ret_tmp10;
      _ref_tmp_4 = &start;
      chpl___ASSIGN_18(_ref_tmp_4, &ret_tmp10);
      (&_init_class_tmp_8)->len = INT64(0);
      (&_init_class_tmp_8)->_size = INT64(0);
      (&_init_class_tmp_8)->buff = nil;
      (&_init_class_tmp_8)->owned = UINT8(false);
      (&_init_class_tmp_8)->locale_id = INT32(0);
      (&this23)->val_chpl = _init_class_tmp_8;
      (&this23)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg5 = chpl__autoCopy6(&local__str_literal_583 /* ", " */);
      (&this23)->val_chpl = wrap_arg5;
      (&this23)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_11 = &ret_tmp11;
      _construct_ioLiteral_chpl(&wrap_arg5, UINT8(true), &this23, ret_to_arg_ref_tmp_11);
      call_tmp13 = ret_tmp11;
      _ref_tmp_5 = &comma;
      chpl___ASSIGN_18(_ref_tmp_5, &ret_tmp11);
      (&_init_class_tmp_9)->len = INT64(0);
      (&_init_class_tmp_9)->_size = INT64(0);
      (&_init_class_tmp_9)->buff = nil;
      (&_init_class_tmp_9)->owned = UINT8(false);
      (&_init_class_tmp_9)->locale_id = INT32(0);
      (&this24)->val_chpl = _init_class_tmp_9;
      (&this24)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg6 = chpl__autoCopy6(&local__str_literal_585 /* "]" */);
      (&this24)->val_chpl = wrap_arg6;
      (&this24)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_12 = &ret_tmp12;
      _construct_ioLiteral_chpl(&wrap_arg6, UINT8(true), &this24, ret_to_arg_ref_tmp_12);
      call_tmp14 = ret_tmp12;
      _ref_tmp_6 = &end;
      chpl___ASSIGN_18(_ref_tmp_6, &ret_tmp12);
      _field_destructor_tmp_4 = &((&call_tmp12)->val_chpl);
      chpl_macro_tmp_613.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_613.addr = _field_destructor_tmp_4;
      T4 = chpl_macro_tmp_613;
      deinit44(T4);
      _field_destructor_tmp_5 = &((&call_tmp13)->val_chpl);
      chpl_macro_tmp_614.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_614.addr = _field_destructor_tmp_5;
      T5 = chpl_macro_tmp_614;
      deinit44(T5);
      _field_destructor_tmp_6 = &((&call_tmp14)->val_chpl);
      chpl_macro_tmp_615.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_615.addr = _field_destructor_tmp_6;
      T6 = chpl_macro_tmp_615;
      deinit44(T6);
    } else {
      (&_init_class_tmp_10)->len = INT64(0);
      (&_init_class_tmp_10)->_size = INT64(0);
      (&_init_class_tmp_10)->buff = nil;
      (&_init_class_tmp_10)->owned = UINT8(false);
      (&_init_class_tmp_10)->locale_id = INT32(0);
      (&this25)->val_chpl = _init_class_tmp_10;
      (&this25)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg7 = chpl__autoCopy6(&local__str_literal_587 /* "(" */);
      (&this25)->val_chpl = wrap_arg7;
      (&this25)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_13 = &ret_tmp13;
      _construct_ioLiteral_chpl(&wrap_arg7, UINT8(true), &this25, ret_to_arg_ref_tmp_13);
      call_tmp15 = ret_tmp13;
      _ref_tmp_7 = &start;
      chpl___ASSIGN_18(_ref_tmp_7, &ret_tmp13);
      (&_init_class_tmp_11)->len = INT64(0);
      (&_init_class_tmp_11)->_size = INT64(0);
      (&_init_class_tmp_11)->buff = nil;
      (&_init_class_tmp_11)->owned = UINT8(false);
      (&_init_class_tmp_11)->locale_id = INT32(0);
      (&this26)->val_chpl = _init_class_tmp_11;
      (&this26)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg8 = chpl__autoCopy6(&local__str_literal_583 /* ", " */);
      (&this26)->val_chpl = wrap_arg8;
      (&this26)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_14 = &ret_tmp14;
      _construct_ioLiteral_chpl(&wrap_arg8, UINT8(true), &this26, ret_to_arg_ref_tmp_14);
      call_tmp16 = ret_tmp14;
      _ref_tmp_8 = &comma;
      chpl___ASSIGN_18(_ref_tmp_8, &ret_tmp14);
      (&_init_class_tmp_12)->len = INT64(0);
      (&_init_class_tmp_12)->_size = INT64(0);
      (&_init_class_tmp_12)->buff = nil;
      (&_init_class_tmp_12)->owned = UINT8(false);
      (&_init_class_tmp_12)->locale_id = INT32(0);
      (&this27)->val_chpl = _init_class_tmp_12;
      (&this27)->ignoreWhiteSpace_chpl = UINT8(false);
      wrap_arg9 = chpl__autoCopy6(&local__str_literal_411 /* ")" */);
      (&this27)->val_chpl = wrap_arg9;
      (&this27)->ignoreWhiteSpace_chpl = UINT8(true);
      ret_to_arg_ref_tmp_15 = &ret_tmp15;
      _construct_ioLiteral_chpl(&wrap_arg9, UINT8(true), &this27, ret_to_arg_ref_tmp_15);
      call_tmp17 = ret_tmp15;
      _ref_tmp_9 = &end;
      chpl___ASSIGN_18(_ref_tmp_9, &ret_tmp15);
      _field_destructor_tmp_7 = &((&call_tmp15)->val_chpl);
      chpl_macro_tmp_616.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_616.addr = _field_destructor_tmp_7;
      T7 = chpl_macro_tmp_616;
      deinit44(T7);
      _field_destructor_tmp_8 = &((&call_tmp16)->val_chpl);
      chpl_macro_tmp_617.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_617.addr = _field_destructor_tmp_8;
      T8 = chpl_macro_tmp_617;
      deinit44(T8);
      _field_destructor_tmp_9 = &((&call_tmp17)->val_chpl);
      chpl_macro_tmp_618.locale = chpl_gen_getLocaleID();
      chpl_macro_tmp_618.addr = _field_destructor_tmp_9;
      T9 = chpl_macro_tmp_618;
      deinit44(T9);
    }
  }
  call_tmp18 = (! call_tmp6);
  if (call_tmp18) {
    writeIt_chpl(f, &start);
  }
  chpl_macro_tmp_619.locale = (this12).locale;
  chpl_macro_tmp_619.addr = &(((this12).addr)->x1);
  chpl_gen_comm_get(((void*)(&T10)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_619).locale), INT64(0), INT32(0)), (chpl_macro_tmp_619).addr, sizeof(chpl_bool), -1, COMMID(0), INT64(265), INT64(20));
  writeIt_chpl3(f, T10);
  call_tmp19 = (! call_tmp6);
  if (call_tmp19) {
    writeIt_chpl(f, &comma);
  }
  chpl_macro_tmp_620.locale = (this12).locale;
  chpl_macro_tmp_620.addr = &(((this12).addr)->x2);
  chpl_gen_comm_get(((void*)(&T11)), chpl_nodeFromLocaleID(&((chpl_macro_tmp_620).locale), INT64(0), INT32(0)), (chpl_macro_tmp_620).addr, sizeof(int64_t), -1, COMMID(1), INT64(270), INT64(20));
  writeIt_chpl2(f, T11);
  call_tmp20 = (! call_tmp6);
  if (call_tmp20) {
    writeIt_chpl(f, &end);
  }
  _field_destructor_tmp_10 = &((&end)->val_chpl);
  chpl_macro_tmp_621.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_621.addr = _field_destructor_tmp_10;
  T12 = chpl_macro_tmp_621;
  deinit44(T12);
  _field_destructor_tmp_11 = &((&comma)->val_chpl);
  chpl_macro_tmp_622.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_622.addr = _field_destructor_tmp_11;
  T13 = chpl_macro_tmp_622;
  deinit44(T13);
  _field_destructor_tmp_12 = &((&start)->val_chpl);
  chpl_macro_tmp_623.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_623.addr = _field_destructor_tmp_12;
  T14 = chpl_macro_tmp_623;
  deinit44(T14);
  return;
}

/* ChapelTuple.chpl:352 */
static void max2(_ref__tuple_1_star_int64_t _retArg) {
  *(*(_retArg) + INT64(0)) = INT64(9223372036854775807);
  return;
}

