/* SysError.chpl:40 */
static void chpl__init_SysError(int64_t _ln_chpl,
                                int32_t _fn_chpl) {
  _ref_int32_t refIndentLevel_chpl = NULL;
  if (chpl__init_SysError_p) {
    goto _exit_chpl__init_SysError_chpl;
  }
  printModuleInit("%*s\n", "SysError", INT64(8));
  refIndentLevel_chpl = &moduleInitLevel;
  *(refIndentLevel_chpl) += INT64(1);
  chpl__init_SysError_p = UINT8(true);
  {
    chpl__init_SysBasic(INT64(40), INT32(75));
  }
  *(refIndentLevel_chpl) -= INT64(1);
  _exit_chpl__init_SysError_chpl:;
  return;
}

/* SysError.chpl:51 */
static c_string quote_string_chpl(_ref_string s_chpl,
                                  int64_t len_chpl) {
  c_void_ptr local_c_nil_chpl;
  string local__str_literal_337_chpl;
  c_string ret_chpl;
  c_string ret_chpl2;
  string call_tmp_chpl;
  string ret_chpl3;
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  string ret_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  _ref_string i_s_chpl = NULL;
  chpl____wide__ref_string tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  string type_tmp_chpl;
  string this_chpl6;
  c_ptr_uint8_t call_tmp_chpl3 = NULL;
  int32_t default_arglocale_id_chpl;
  string ret_tmp_chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  _ref_string _ref_tmp__chpl = NULL;
  _ref_string i_rhs_chpl = NULL;
  chpl____wide__ref_string tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl4;
  c_ptr_uint8_t coerce_tmp_chpl2 = NULL;
  syserr call_tmp_chpl5;
  _ref_c_string _ref_tmp__chpl2 = NULL;
  int32_t call_tmp_chpl6;
  chpl_bool call_tmp_chpl7;
  c_string call_tmp_chpl8;
  _ref_string _ref_tmp__chpl3 = NULL;
  chpl____wide__ref_string tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl4 = NULL;
  chpl____wide__ref_string tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string chpl_macro_tmp_7776;
  chpl____wide__ref_string chpl_macro_tmp_7777;
  chpl____wide__ref_string chpl_macro_tmp_7778;
  chpl____wide__ref_string chpl_macro_tmp_7779;
  chpl____wide__ref_string chpl_macro_tmp_7780;
  local_c_nil_chpl = c_nil;
  local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */ = _str_literal_337 /* "Cannot call .c_str() on a remote string" */;
  ret_chpl2 = "";
  coerce_tmp_chpl = (s_chpl)->locale_id;
  call_tmp_chpl2 = (coerce_tmp_chpl == chpl_nodeID);
  if (call_tmp_chpl2) {
    ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
    i_s_chpl = s_chpl;
    chpl_macro_tmp_7776.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7776.addr = i_s_chpl;
    tmp_chpl = chpl_macro_tmp_7776;
    string2(tmp_chpl, UINT8(false), ret_to_arg_ref_tmp__chpl);
    ret_chpl3 = ret_tmp_chpl;
    goto _end_localize_chpl;
  } else {
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    (&this_chpl6)->buff = nil;
    (&this_chpl6)->owned = UINT8(false);
    (&this_chpl6)->locale_id = INT32(0);
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    call_tmp_chpl3 = ((c_ptr_uint8_t)(nil));
    (&this_chpl6)->buff = call_tmp_chpl3;
    (&this_chpl6)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl6)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl3, UINT8(true), default_arglocale_id_chpl, &this_chpl6, ret_to_arg_ref_tmp__chpl2);
    type_tmp_chpl = ret_tmp_chpl2;
    _ref_tmp__chpl = &type_tmp_chpl;
    i_rhs_chpl = s_chpl;
    chpl_macro_tmp_7777.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7777.addr = _ref_tmp__chpl;
    tmp_chpl2 = chpl_macro_tmp_7777;
    chpl_macro_tmp_7778.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7778.addr = i_rhs_chpl;
    tmp_chpl3 = chpl_macro_tmp_7778;
    chpl___ASSIGN_13(tmp_chpl2, tmp_chpl3);
    ret_chpl3 = type_tmp_chpl;
    goto _end_localize_chpl;
  }
  _end_localize_chpl:;
  call_tmp_chpl = ret_chpl3;
  call_tmp_chpl4 = ((&call_tmp_chpl)->locale_id != chpl_nodeID);
  if (call_tmp_chpl4) {
    halt(&local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */, INT64(62), INT32(75));
  }
  coerce_tmp_chpl2 = (&call_tmp_chpl)->buff;
  _ref_tmp__chpl2 = &ret_chpl2;
  call_tmp_chpl5 = qio_quote_string(UINT8(34), UINT8(34), QIO_STRING_FORMAT_CHPL, ((c_string)(((c_void_ptr)(coerce_tmp_chpl2)))), len_chpl, _ref_tmp__chpl2, local_c_nil_chpl);
  call_tmp_chpl6 = qio_err_iserr(call_tmp_chpl5);
  call_tmp_chpl7 = (call_tmp_chpl6 != INT32(0));
  if (call_tmp_chpl7) {
    call_tmp_chpl8 = qio_strdup("<error>");
    ret_chpl = call_tmp_chpl8;
    _ref_tmp__chpl3 = &call_tmp_chpl;
    chpl_macro_tmp_7779.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7779.addr = _ref_tmp__chpl3;
    tmp_chpl4 = chpl_macro_tmp_7779;
    deinit44(tmp_chpl4);
    goto _end_quote_string_chpl;
  }
  ret_chpl = ret_chpl2;
  _ref_tmp__chpl4 = &call_tmp_chpl;
  chpl_macro_tmp_7780.locale = chpl_gen_getLocaleID();
  chpl_macro_tmp_7780.addr = _ref_tmp__chpl4;
  tmp_chpl5 = chpl_macro_tmp_7780;
  deinit44(tmp_chpl5);
  _end_quote_string_chpl:;
  return ret_chpl;
}

/* SysError.chpl:78 */
static void ioerror_chpl(syserr error_chpl,
                         _ref_string msg_chpl) {
  string local__str_literal_337_chpl;
  string local__str_literal_400_chpl;
  int32_t call_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  int32_t strerror_err_chpl;
  c_string call_tmp_chpl3;
  _ref_int32_t _ref_tmp__chpl = NULL;
  string err_msg_chpl;
  string type_tmp_chpl;
  string this_chpl6;
  c_ptr_uint8_t call_tmp_chpl4 = NULL;
  int32_t default_arglocale_id_chpl;
  string ret_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  string call_tmp_chpl5;
  string ret_tmp_chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  string call_tmp_chpl6;
  string ret_tmp_chpl3;
  _ref_string ret_to_arg_ref_tmp__chpl3 = NULL;
  string call_tmp_chpl7;
  string ret_tmp_chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl4 = NULL;
  _ref_string _ref_tmp__chpl2 = NULL;
  chpl____wide__ref_string tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl8;
  c_ptr_uint8_t coerce_tmp_chpl2 = NULL;
  _ref_string _ref_tmp__chpl3 = NULL;
  chpl____wide__ref_string tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl4 = NULL;
  chpl____wide__ref_string tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl5 = NULL;
  chpl____wide__ref_string tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl6 = NULL;
  chpl____wide__ref_string tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string chpl_macro_tmp_7781;
  chpl____wide__ref_string chpl_macro_tmp_7782;
  chpl____wide__ref_string chpl_macro_tmp_7783;
  chpl____wide__ref_string chpl_macro_tmp_7784;
  chpl____wide__ref_string chpl_macro_tmp_7785;
  chpl____wide__ref_string chpl_macro_tmp_7786;
  local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */ = _str_literal_337 /* "Cannot call .c_str() on a remote string" */;
  local__str_literal_400_chpl /* " " */ = _str_literal_400 /* " " */;
  call_tmp_chpl = qio_err_iserr(error_chpl);
  call_tmp_chpl2 = (call_tmp_chpl != INT32(0));
  if (call_tmp_chpl2) {
    strerror_err_chpl = INT32(0);
    _ref_tmp__chpl = &strerror_err_chpl;
    call_tmp_chpl3 = sys_strerror_syserr_str(error_chpl, _ref_tmp__chpl);
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    (&this_chpl6)->buff = nil;
    (&this_chpl6)->owned = UINT8(false);
    (&this_chpl6)->locale_id = INT32(0);
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    call_tmp_chpl4 = ((c_ptr_uint8_t)(nil));
    (&this_chpl6)->buff = call_tmp_chpl4;
    (&this_chpl6)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl6)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl4, UINT8(true), default_arglocale_id_chpl, &this_chpl6, ret_to_arg_ref_tmp__chpl);
    type_tmp_chpl = ret_tmp_chpl;
    ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
    _cast(call_tmp_chpl3, ret_to_arg_ref_tmp__chpl2);
    call_tmp_chpl5 = ret_tmp_chpl2;
    ret_to_arg_ref_tmp__chpl3 = &ret_tmp_chpl3;
    chpl___PLUS_(&ret_tmp_chpl2, &local__str_literal_400_chpl /* " " */, ret_to_arg_ref_tmp__chpl3);
    call_tmp_chpl6 = ret_tmp_chpl3;
    ret_to_arg_ref_tmp__chpl4 = &ret_tmp_chpl4;
    chpl___PLUS_(&ret_tmp_chpl3, msg_chpl, ret_to_arg_ref_tmp__chpl4);
    call_tmp_chpl7 = ret_tmp_chpl4;
    _ref_tmp__chpl2 = &type_tmp_chpl;
    chpl_macro_tmp_7781.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7781.addr = _ref_tmp__chpl2;
    tmp_chpl = chpl_macro_tmp_7781;
    chpl_macro_tmp_7782.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7782.addr = &ret_tmp_chpl4;
    tmp_chpl2 = chpl_macro_tmp_7782;
    chpl___ASSIGN_13(tmp_chpl, tmp_chpl2);
    err_msg_chpl = type_tmp_chpl;
    coerce_tmp_chpl = (&err_msg_chpl)->locale_id;
    call_tmp_chpl8 = (coerce_tmp_chpl != chpl_nodeID);
    if (call_tmp_chpl8) {
      halt(&local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */, INT64(85), INT32(75));
    }
    coerce_tmp_chpl2 = (&err_msg_chpl)->buff;
    chpl_error(((c_string)(((c_void_ptr)(coerce_tmp_chpl2)))), INT64(85), INT32(75));
    _ref_tmp__chpl3 = &err_msg_chpl;
    chpl_macro_tmp_7783.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7783.addr = _ref_tmp__chpl3;
    tmp_chpl3 = chpl_macro_tmp_7783;
    deinit44(tmp_chpl3);
    _ref_tmp__chpl4 = &call_tmp_chpl5;
    chpl_macro_tmp_7784.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7784.addr = _ref_tmp__chpl4;
    tmp_chpl4 = chpl_macro_tmp_7784;
    deinit44(tmp_chpl4);
    _ref_tmp__chpl5 = &call_tmp_chpl6;
    chpl_macro_tmp_7785.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7785.addr = _ref_tmp__chpl5;
    tmp_chpl5 = chpl_macro_tmp_7785;
    deinit44(tmp_chpl5);
    _ref_tmp__chpl6 = &call_tmp_chpl7;
    chpl_macro_tmp_7786.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7786.addr = _ref_tmp__chpl6;
    tmp_chpl6 = chpl_macro_tmp_7786;
    deinit44(tmp_chpl6);
  }
  return;
}

/* SysError.chpl:99 */
static void ioerror_chpl2(syserr error_chpl,
                          _ref_string msg_chpl,
                          _ref_string path_chpl) {
  string local__str_literal_337_chpl;
  string local__str_literal_2823_chpl;
  string local__str_literal_400_chpl;
  int32_t call_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  int32_t strerror_err_chpl;
  string errstr_chpl;
  c_string call_tmp_chpl3;
  _ref_int32_t _ref_tmp__chpl = NULL;
  string ret_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  string quotedpath_chpl;
  int64_t ret_chpl;
  c_string call_tmp_chpl4;
  string ret_tmp_chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  string err_msg_chpl;
  string type_tmp_chpl;
  string this_chpl6;
  c_ptr_uint8_t call_tmp_chpl5 = NULL;
  int32_t default_arglocale_id_chpl;
  string ret_tmp_chpl3;
  _ref_string ret_to_arg_ref_tmp__chpl3 = NULL;
  string call_tmp_chpl6;
  string ret_tmp_chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl4 = NULL;
  string call_tmp_chpl7;
  string ret_tmp_chpl5;
  _ref_string ret_to_arg_ref_tmp__chpl5 = NULL;
  string call_tmp_chpl8;
  string ret_tmp_chpl6;
  _ref_string ret_to_arg_ref_tmp__chpl6 = NULL;
  string call_tmp_chpl9;
  string ret_tmp_chpl7;
  _ref_string ret_to_arg_ref_tmp__chpl7 = NULL;
  _ref_string _ref_tmp__chpl2 = NULL;
  chpl____wide__ref_string tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl_bool call_tmp_chpl10;
  _ref_string _ref_tmp__chpl3 = NULL;
  chpl____wide__ref_string tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl4 = NULL;
  chpl____wide__ref_string tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl5 = NULL;
  chpl____wide__ref_string tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl6 = NULL;
  chpl____wide__ref_string tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl7 = NULL;
  chpl____wide__ref_string tmp_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl8 = NULL;
  chpl____wide__ref_string tmp_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl9 = NULL;
  chpl____wide__ref_string tmp_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string chpl_macro_tmp_7787;
  chpl____wide__ref_string chpl_macro_tmp_7788;
  chpl____wide__ref_string chpl_macro_tmp_7789;
  chpl____wide__ref_string chpl_macro_tmp_7790;
  chpl____wide__ref_string chpl_macro_tmp_7791;
  chpl____wide__ref_string chpl_macro_tmp_7792;
  chpl____wide__ref_string chpl_macro_tmp_7793;
  chpl____wide__ref_string chpl_macro_tmp_7794;
  chpl____wide__ref_string chpl_macro_tmp_7795;
  local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */ = _str_literal_337 /* "Cannot call .c_str() on a remote string" */;
  local__str_literal_2823_chpl /* " with path " */ = _str_literal_2823 /* " with path " */;
  local__str_literal_400_chpl /* " " */ = _str_literal_400 /* " " */;
  call_tmp_chpl = qio_err_iserr(error_chpl);
  call_tmp_chpl2 = (call_tmp_chpl != INT32(0));
  if (call_tmp_chpl2) {
    strerror_err_chpl = INT32(0);
    _ref_tmp__chpl = &strerror_err_chpl;
    call_tmp_chpl3 = sys_strerror_syserr_str(error_chpl, _ref_tmp__chpl);
    ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
    _cast(call_tmp_chpl3, ret_to_arg_ref_tmp__chpl);
    errstr_chpl = ret_tmp_chpl;
    ret_chpl = (path_chpl)->len;
    call_tmp_chpl4 = quote_string_chpl(path_chpl, ret_chpl);
    ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
    _cast(call_tmp_chpl4, ret_to_arg_ref_tmp__chpl2);
    quotedpath_chpl = ret_tmp_chpl2;
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    (&this_chpl6)->buff = nil;
    (&this_chpl6)->owned = UINT8(false);
    (&this_chpl6)->locale_id = INT32(0);
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    call_tmp_chpl5 = ((c_ptr_uint8_t)(nil));
    (&this_chpl6)->buff = call_tmp_chpl5;
    (&this_chpl6)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl6)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl3 = &ret_tmp_chpl3;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl5, UINT8(true), default_arglocale_id_chpl, &this_chpl6, ret_to_arg_ref_tmp__chpl3);
    type_tmp_chpl = ret_tmp_chpl3;
    ret_to_arg_ref_tmp__chpl4 = &ret_tmp_chpl4;
    chpl___PLUS_(&ret_tmp_chpl, &local__str_literal_400_chpl /* " " */, ret_to_arg_ref_tmp__chpl4);
    call_tmp_chpl6 = ret_tmp_chpl4;
    ret_to_arg_ref_tmp__chpl5 = &ret_tmp_chpl5;
    chpl___PLUS_(&ret_tmp_chpl4, msg_chpl, ret_to_arg_ref_tmp__chpl5);
    call_tmp_chpl7 = ret_tmp_chpl5;
    ret_to_arg_ref_tmp__chpl6 = &ret_tmp_chpl6;
    chpl___PLUS_(&ret_tmp_chpl5, &local__str_literal_2823_chpl /* " with path " */, ret_to_arg_ref_tmp__chpl6);
    call_tmp_chpl8 = ret_tmp_chpl6;
    ret_to_arg_ref_tmp__chpl7 = &ret_tmp_chpl7;
    chpl___PLUS_(&ret_tmp_chpl6, &ret_tmp_chpl2, ret_to_arg_ref_tmp__chpl7);
    call_tmp_chpl9 = ret_tmp_chpl7;
    _ref_tmp__chpl2 = &type_tmp_chpl;
    chpl_macro_tmp_7787.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7787.addr = _ref_tmp__chpl2;
    tmp_chpl = chpl_macro_tmp_7787;
    chpl_macro_tmp_7788.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7788.addr = &ret_tmp_chpl7;
    tmp_chpl2 = chpl_macro_tmp_7788;
    chpl___ASSIGN_13(tmp_chpl, tmp_chpl2);
    err_msg_chpl = type_tmp_chpl;
    call_tmp_chpl10 = ((&err_msg_chpl)->locale_id != chpl_nodeID);
    if (call_tmp_chpl10) {
      halt(&local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */, INT64(106), INT32(75));
    }
    chpl_error(((c_string)(((c_void_ptr)((&err_msg_chpl)->buff)))), INT64(106), INT32(75));
    _ref_tmp__chpl3 = &errstr_chpl;
    chpl_macro_tmp_7789.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7789.addr = _ref_tmp__chpl3;
    tmp_chpl3 = chpl_macro_tmp_7789;
    deinit44(tmp_chpl3);
    _ref_tmp__chpl4 = &quotedpath_chpl;
    chpl_macro_tmp_7790.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7790.addr = _ref_tmp__chpl4;
    tmp_chpl4 = chpl_macro_tmp_7790;
    deinit44(tmp_chpl4);
    _ref_tmp__chpl5 = &err_msg_chpl;
    chpl_macro_tmp_7791.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7791.addr = _ref_tmp__chpl5;
    tmp_chpl5 = chpl_macro_tmp_7791;
    deinit44(tmp_chpl5);
    _ref_tmp__chpl6 = &call_tmp_chpl6;
    chpl_macro_tmp_7792.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7792.addr = _ref_tmp__chpl6;
    tmp_chpl6 = chpl_macro_tmp_7792;
    deinit44(tmp_chpl6);
    _ref_tmp__chpl7 = &call_tmp_chpl7;
    chpl_macro_tmp_7793.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7793.addr = _ref_tmp__chpl7;
    tmp_chpl7 = chpl_macro_tmp_7793;
    deinit44(tmp_chpl7);
    _ref_tmp__chpl8 = &call_tmp_chpl8;
    chpl_macro_tmp_7794.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7794.addr = _ref_tmp__chpl8;
    tmp_chpl8 = chpl_macro_tmp_7794;
    deinit44(tmp_chpl8);
    _ref_tmp__chpl9 = &call_tmp_chpl9;
    chpl_macro_tmp_7795.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7795.addr = _ref_tmp__chpl9;
    tmp_chpl9 = chpl_macro_tmp_7795;
    deinit44(tmp_chpl9);
  }
  return;
}

/* SysError.chpl:121 */
static void ioerror_chpl3(syserr error_chpl,
                          _ref_string msg_chpl,
                          _ref_string path_chpl,
                          int64_t offset_chpl2) {
  string local__str_literal_337_chpl;
  string local__str_literal_2825_chpl;
  string local__str_literal_2823_chpl;
  string local__str_literal_400_chpl;
  int32_t call_tmp_chpl;
  chpl_bool call_tmp_chpl2;
  int32_t strerror_err_chpl;
  string errstr_chpl;
  c_string call_tmp_chpl3;
  _ref_int32_t _ref_tmp__chpl = NULL;
  string ret_tmp_chpl;
  _ref_string ret_to_arg_ref_tmp__chpl = NULL;
  string quotedpath_chpl;
  c_string call_tmp_chpl4;
  string ret_tmp_chpl2;
  _ref_string ret_to_arg_ref_tmp__chpl2 = NULL;
  string err_msg_chpl;
  string type_tmp_chpl;
  string this_chpl6;
  c_ptr_uint8_t call_tmp_chpl5 = NULL;
  int32_t default_arglocale_id_chpl;
  string ret_tmp_chpl3;
  _ref_string ret_to_arg_ref_tmp__chpl3 = NULL;
  string call_tmp_chpl6;
  string ret_tmp_chpl4;
  _ref_string ret_to_arg_ref_tmp__chpl4 = NULL;
  string call_tmp_chpl7;
  string ret_tmp_chpl5;
  _ref_string ret_to_arg_ref_tmp__chpl5 = NULL;
  string call_tmp_chpl8;
  string ret_tmp_chpl6;
  _ref_string ret_to_arg_ref_tmp__chpl6 = NULL;
  string call_tmp_chpl9;
  string ret_tmp_chpl7;
  _ref_string ret_to_arg_ref_tmp__chpl7 = NULL;
  string call_tmp_chpl10;
  string ret_tmp_chpl8;
  _ref_string ret_to_arg_ref_tmp__chpl8 = NULL;
  string call_tmp_chpl11;
  string ret_tmp_chpl9;
  _ref_string ret_to_arg_ref_tmp__chpl9 = NULL;
  string call_tmp_chpl12;
  string ret_tmp_chpl10;
  _ref_string ret_to_arg_ref_tmp__chpl10 = NULL;
  _ref_string _ref_tmp__chpl2 = NULL;
  chpl____wide__ref_string tmp_chpl = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string tmp_chpl2 = {CHPL_LOCALEID_T_INIT, NULL};
  int32_t coerce_tmp_chpl;
  chpl_bool call_tmp_chpl13;
  _ref_string _ref_tmp__chpl3 = NULL;
  chpl____wide__ref_string tmp_chpl3 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl4 = NULL;
  chpl____wide__ref_string tmp_chpl4 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl5 = NULL;
  chpl____wide__ref_string tmp_chpl5 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl6 = NULL;
  chpl____wide__ref_string tmp_chpl6 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl7 = NULL;
  chpl____wide__ref_string tmp_chpl7 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl8 = NULL;
  chpl____wide__ref_string tmp_chpl8 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl9 = NULL;
  chpl____wide__ref_string tmp_chpl9 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl10 = NULL;
  chpl____wide__ref_string tmp_chpl10 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl11 = NULL;
  chpl____wide__ref_string tmp_chpl11 = {CHPL_LOCALEID_T_INIT, NULL};
  _ref_string _ref_tmp__chpl12 = NULL;
  chpl____wide__ref_string tmp_chpl12 = {CHPL_LOCALEID_T_INIT, NULL};
  chpl____wide__ref_string chpl_macro_tmp_7796;
  chpl____wide__ref_string chpl_macro_tmp_7797;
  chpl____wide__ref_string chpl_macro_tmp_7798;
  chpl____wide__ref_string chpl_macro_tmp_7799;
  chpl____wide__ref_string chpl_macro_tmp_7800;
  chpl____wide__ref_string chpl_macro_tmp_7801;
  chpl____wide__ref_string chpl_macro_tmp_7802;
  chpl____wide__ref_string chpl_macro_tmp_7803;
  chpl____wide__ref_string chpl_macro_tmp_7804;
  chpl____wide__ref_string chpl_macro_tmp_7805;
  chpl____wide__ref_string chpl_macro_tmp_7806;
  chpl____wide__ref_string chpl_macro_tmp_7807;
  local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */ = _str_literal_337 /* "Cannot call .c_str() on a remote string" */;
  local__str_literal_2825_chpl /* " offset " */ = _str_literal_2825 /* " offset " */;
  local__str_literal_2823_chpl /* " with path " */ = _str_literal_2823 /* " with path " */;
  local__str_literal_400_chpl /* " " */ = _str_literal_400 /* " " */;
  call_tmp_chpl = qio_err_iserr(error_chpl);
  call_tmp_chpl2 = (call_tmp_chpl != INT32(0));
  if (call_tmp_chpl2) {
    strerror_err_chpl = INT32(0);
    _ref_tmp__chpl = &strerror_err_chpl;
    call_tmp_chpl3 = sys_strerror_syserr_str(error_chpl, _ref_tmp__chpl);
    ret_to_arg_ref_tmp__chpl = &ret_tmp_chpl;
    _cast(call_tmp_chpl3, ret_to_arg_ref_tmp__chpl);
    errstr_chpl = ret_tmp_chpl;
    call_tmp_chpl4 = quote_string_chpl(path_chpl, (path_chpl)->len);
    ret_to_arg_ref_tmp__chpl2 = &ret_tmp_chpl2;
    _cast(call_tmp_chpl4, ret_to_arg_ref_tmp__chpl2);
    quotedpath_chpl = ret_tmp_chpl2;
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    (&this_chpl6)->buff = nil;
    (&this_chpl6)->owned = UINT8(false);
    (&this_chpl6)->locale_id = INT32(0);
    (&this_chpl6)->len = INT64(0);
    (&this_chpl6)->_size = INT64(0);
    call_tmp_chpl5 = ((c_ptr_uint8_t)(nil));
    (&this_chpl6)->buff = call_tmp_chpl5;
    (&this_chpl6)->owned = UINT8(true);
    default_arglocale_id_chpl = chpl_nodeID;
    (&this_chpl6)->locale_id = default_arglocale_id_chpl;
    ret_to_arg_ref_tmp__chpl3 = &ret_tmp_chpl3;
    _construct_string(INT64(0), INT64(0), call_tmp_chpl5, UINT8(true), default_arglocale_id_chpl, &this_chpl6, ret_to_arg_ref_tmp__chpl3);
    type_tmp_chpl = ret_tmp_chpl3;
    ret_to_arg_ref_tmp__chpl4 = &ret_tmp_chpl4;
    chpl___PLUS_(&ret_tmp_chpl, &local__str_literal_400_chpl /* " " */, ret_to_arg_ref_tmp__chpl4);
    call_tmp_chpl6 = ret_tmp_chpl4;
    ret_to_arg_ref_tmp__chpl5 = &ret_tmp_chpl5;
    chpl___PLUS_(&ret_tmp_chpl4, msg_chpl, ret_to_arg_ref_tmp__chpl5);
    call_tmp_chpl7 = ret_tmp_chpl5;
    ret_to_arg_ref_tmp__chpl6 = &ret_tmp_chpl6;
    chpl___PLUS_(&ret_tmp_chpl5, &local__str_literal_2823_chpl /* " with path " */, ret_to_arg_ref_tmp__chpl6);
    call_tmp_chpl8 = ret_tmp_chpl6;
    ret_to_arg_ref_tmp__chpl7 = &ret_tmp_chpl7;
    chpl___PLUS_(&ret_tmp_chpl6, &ret_tmp_chpl2, ret_to_arg_ref_tmp__chpl7);
    call_tmp_chpl9 = ret_tmp_chpl7;
    ret_to_arg_ref_tmp__chpl8 = &ret_tmp_chpl8;
    chpl___PLUS_(&ret_tmp_chpl7, &local__str_literal_2825_chpl /* " offset " */, ret_to_arg_ref_tmp__chpl8);
    call_tmp_chpl10 = ret_tmp_chpl8;
    ret_to_arg_ref_tmp__chpl9 = &ret_tmp_chpl9;
    _cast3(offset_chpl2, ret_to_arg_ref_tmp__chpl9);
    call_tmp_chpl11 = ret_tmp_chpl9;
    ret_to_arg_ref_tmp__chpl10 = &ret_tmp_chpl10;
    chpl___PLUS_(&ret_tmp_chpl8, &ret_tmp_chpl9, ret_to_arg_ref_tmp__chpl10);
    call_tmp_chpl12 = ret_tmp_chpl10;
    _ref_tmp__chpl2 = &type_tmp_chpl;
    chpl_macro_tmp_7796.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7796.addr = _ref_tmp__chpl2;
    tmp_chpl = chpl_macro_tmp_7796;
    chpl_macro_tmp_7797.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7797.addr = &ret_tmp_chpl10;
    tmp_chpl2 = chpl_macro_tmp_7797;
    chpl___ASSIGN_13(tmp_chpl, tmp_chpl2);
    err_msg_chpl = type_tmp_chpl;
    coerce_tmp_chpl = (&err_msg_chpl)->locale_id;
    call_tmp_chpl13 = (coerce_tmp_chpl != chpl_nodeID);
    if (call_tmp_chpl13) {
      halt(&local__str_literal_337_chpl /* "Cannot call .c_str() on a remote string" */, INT64(128), INT32(75));
    }
    chpl_error(((c_string)(((c_void_ptr)((&err_msg_chpl)->buff)))), INT64(128), INT32(75));
    _ref_tmp__chpl3 = &errstr_chpl;
    chpl_macro_tmp_7798.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7798.addr = _ref_tmp__chpl3;
    tmp_chpl3 = chpl_macro_tmp_7798;
    deinit44(tmp_chpl3);
    _ref_tmp__chpl4 = &quotedpath_chpl;
    chpl_macro_tmp_7799.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7799.addr = _ref_tmp__chpl4;
    tmp_chpl4 = chpl_macro_tmp_7799;
    deinit44(tmp_chpl4);
    _ref_tmp__chpl5 = &err_msg_chpl;
    chpl_macro_tmp_7800.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7800.addr = _ref_tmp__chpl5;
    tmp_chpl5 = chpl_macro_tmp_7800;
    deinit44(tmp_chpl5);
    _ref_tmp__chpl6 = &call_tmp_chpl6;
    chpl_macro_tmp_7801.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7801.addr = _ref_tmp__chpl6;
    tmp_chpl6 = chpl_macro_tmp_7801;
    deinit44(tmp_chpl6);
    _ref_tmp__chpl7 = &call_tmp_chpl7;
    chpl_macro_tmp_7802.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7802.addr = _ref_tmp__chpl7;
    tmp_chpl7 = chpl_macro_tmp_7802;
    deinit44(tmp_chpl7);
    _ref_tmp__chpl8 = &call_tmp_chpl8;
    chpl_macro_tmp_7803.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7803.addr = _ref_tmp__chpl8;
    tmp_chpl8 = chpl_macro_tmp_7803;
    deinit44(tmp_chpl8);
    _ref_tmp__chpl9 = &call_tmp_chpl9;
    chpl_macro_tmp_7804.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7804.addr = _ref_tmp__chpl9;
    tmp_chpl9 = chpl_macro_tmp_7804;
    deinit44(tmp_chpl9);
    _ref_tmp__chpl10 = &call_tmp_chpl10;
    chpl_macro_tmp_7805.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7805.addr = _ref_tmp__chpl10;
    tmp_chpl10 = chpl_macro_tmp_7805;
    deinit44(tmp_chpl10);
    _ref_tmp__chpl11 = &call_tmp_chpl11;
    chpl_macro_tmp_7806.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7806.addr = _ref_tmp__chpl11;
    tmp_chpl11 = chpl_macro_tmp_7806;
    deinit44(tmp_chpl11);
    _ref_tmp__chpl12 = &call_tmp_chpl12;
    chpl_macro_tmp_7807.locale = chpl_gen_getLocaleID();
    chpl_macro_tmp_7807.addr = _ref_tmp__chpl12;
    tmp_chpl12 = chpl_macro_tmp_7807;
    deinit44(tmp_chpl12);
  }
  return;
}

